# Stage 1: Build
FROM node:lts-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install --silent
COPY . .

ARG PUBLIC_VAPID_KEY
ARG PRIVATE_VAPID_KEY
ARG AUTH_SECRET
ARG AUTH_TRUST_HOST
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG IGNORE_BUILD_ERRORS
ARG FAKE_AUTH
ARG MYSQL_HOST
ARG MYSQL_PORT
ARG MYSQL_DATABASE
ARG MYSQL_USER
ARG MYSQL_PASSWORD

ENV PUBLIC_VAPID_KEY=$PUBLIC_VAPID_KEY
ENV PRIVATE_VAPID_KEY=$PRIVATE_VAPID_KEY
ENV AUTH_SECRET=$AUTH_SECRET
ENV AUTH_TRUST_HOST=$AUTH_TRUST_HOST
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV IGNORE_BUILD_ERRORS=$IGNORE_BUILD_ERRORS
ENV FAKE_AUTH=$FAKE_AUTH
ENV MYSQL_HOST=$MYSQL_HOST
ENV MYSQL_PORT=$MYSQL_PORT
ENV MYSQL_DATABASE=$MYSQL_DATABASE
ENV MYSQL_USER=$MYSQL_USER
ENV MYSQL_PASSWORD=$MYSQL_PASSWORD

RUN npm run build

# Stage 2: Production
FROM node:lts-alpine
WORKDIR /app
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app .
EXPOSE 3000
CMD ["npm", "start"]
