version: "3.8"
services:
  app:
    image: ghcr.io/sibosi/e5vosdo-snimrod:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    deploy:
      mode: replicated
      replicas: 3

    watchtower:
      image: containrrr/watchtower
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      restart: unless-stopped
      command: --cleanup --interval 300
