module.exports = {
  apps: [
    {
      name: "e5vosdo-snimrod",
      script: "node_modules/next/dist/bin/next",
      args: "start",
      instances: "max",
      exec_mode: "cluster",
      cwd: "/app/",
      env: {
        NODE_ENV: "production",
        AUTH_SECRET: process.env.AUTH_SECRET,
        AUTH_TRUST_HOST: process.env.AUTH_TRUST_HOST,
        GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
        GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
        BACKUP_FOLDER_ID: process.env.BACKUP_FOLDER_ID,
        SERVICE_ACCOUNT_KEY: process.env.SERVICE_ACCOUNT_KEY,
        SERVICE_ACCOUNT_KEY_PATH: process.env.SERVICE_ACCOUNT_KEY_PATH,
        IGNORE_BUILD_ERRORS: process.env.IGNORE_BUILD_ERRORS,
        FAKE_AUTH: process.env.FAKE_AUTH,
        MYSQL_HOST: process.env.MYSQL_HOST,
        MYSQL_PORT: process.env.MYSQL_PORT,
        MYSQL_DATABASE: process.env.MYSQL_DATABASE,
        MYSQL_USER: process.env.MYSQL_USER,
        MYSQL_PASSWORD: process.env.MYSQL_PASSWORD,
        ENCRYPTION_PASSWORD: process.env.ENCRYPTION_PASSWORD,
        NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
        NEXT_PUBLIC_SUPABASE_ANON_KEY:
          process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
        SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
        PUBLIC_VAPID_KEY: process.env.PUBLIC_VAPID_KEY,
        PRIVATE_VAPID_KEY: process.env.PRIVATE_VAPID_KEY,
      },
    },
  ],
};
