CREATE TABLE IF NOT EXISTS draft_user_codes (
    email VARCHAR(255) PRIMARY KEY NOT NULL UNIQUE,
    EJG_code CHAR(13) UNIQUE NOT NULL,
    OM5 CHAR(5),
    OM CHAR(11) NOT NULL -- F.e. "XXXXXX12345"
) ENGINE = InnoDB DEFAULT CHARSET = utf8;
CREATE TRIGGER before_insert_draft_user_codes BEFORE INSERT ON draft_user_codes
FOR EACH ROW
BEGIN
    SET NEW.OM5 = SUBSTRING(NEW.OM, 7, 5);
END;
