CREATE TABLE IF NOT EXISTS draft_user_codes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255),
    full_name VARCHAR(255),
    EJG_code CHAR(13),
    OM CHAR(11) NOT NULL, -- F.e. "XXXXXX12345"
    OM5 CHAR(5) GENERATED ALWAYS AS (SUBSTRING(OM, 7, 5)) STORED
) ENGINE = InnoDB DEFAULT CHARSET = utf8;
