DROP TABLE IF EXISTS signups;
CREATE TABLE IF NOT EXISTS signups (
    id INT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL,
    slot_id INT NOT NULL,
    presentation_id INT NOT NULL
);

--@block
SELECT * FROM signups;


--@block
DROP TABLE IF EXISTS presentations;
CREATE TABLE IF NOT EXISTS presentations (
    id INT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    slot_id INT NOT NULL,
    location_id INT NOT NULL,
    signup_type VARCHAR(255) NOT NULL,
    is_competition BOOLEAN NOT NULL DEFAULT 0,
    organiser VARCHAR(255) NOT NULL,
    capacity INT NOT NULL,
    starts_at VARCHAR(255) NOT NULL,
    ends_at VARCHAR(255) NOT NULL,
    signup_deadline VARCHAR(255) NOT NULL,
    min_team_size INT,
    max_team_size INT,
    root_parent INT,
    direct_child INT
);

INSERT INTO `presentations`(`id`,`name`,`description`,`slot_id`,`location_id`,`signup_type`,`is_competition`,`organiser`,`capacity`,`starts_at` ,`ends_at`,`signup_deadline`,`min_team_size`,`max_team_size`,`root_parent`,`direct_child`) VALUES 
('100','Az elemi részecskék színes világa','Az elemi részecske kifejezés hallatán ilyesmik juthatnak eszünkbe: proton, neutron, elektron, esetleg kvark vagy Higgs-bozon. Az elemi részecskék világa azonban még ennél is sokszínűbb. Mi építi fel a körülöttünk lévő világot? Miért színesek a kvarkok? Mi az a Higgs-bozon? És hogyan illik bele a képbe a gravitáció? Ezeknek a kérdéseknek a megválaszolásával egy kis ízelítőt kaphatunk a parányok titokzatos világából','11','0','user','0','Bartucz Eszter (12. D)','0','2024-10-24 09:00:00','2024-10-24 09:45:00','2024-10-23 20:00:00',NULL,NULL,NULL,NULL),
('101','Mindent a (kész)pénzről ','A hagyományos pénzektől az előadás során eljutunk a modern elektronikus pénzekig, és az elektronikus fizetésig. A tudásotokra, ismereteitekre és a véleményetekre is szükség lesz a játékok alatt','11','0','user','0','Dr. Bódi-Schubert Anikó közgazdász, főosztályvezető (Magyar Nemzeti Bank)','30','2024-10-24 09:00:00','2024-10-24 09:45:00','2024-10-24 20:00:00',NULL,NULL,NULL,125),
('102','(Hogyan ne legyél) idiótákkal körülvéve? - A DISC rendszer személyiségtípusai ','Thomas Erikson "Idiótákkal körülvéve" című könyvében leírt DISC személyiségtípusokról fogok beszélni. Hogyan kell viszonyulni bizonyos embertípusokhoz? Hogyan lehet megérteni azokat az embereket, akiknek számodra értelmezhetetlenek a gondolatmenetei? Hogyan lehet jó csapatot építeni belőlük? Milyen egy jó csapat? Beszélek önismeretről is, hogyan használjuk személységtípusaink erősségeit, és hogyan javítsunk a gyengébb részein','11','0','user','0','Czakó Anna (11. E)','30','2024-10-24 09:00:00','2024-10-24 09:45:00','2024-10-25 20:00:00',NULL,NULL,NULL,126),
('103','Mi fán terem a vallás? ','Gondolkodtál már azon, hogy mi is az a "vallás"? Mire jó? Miért hisz több milliárd ember valami(k)ben, ami(k)re semmi bizonyítéka nincs? Érdekel, mitől lesz valami "szent", vagy épp fordítva, mitől lesz profánná? Sokszor hallod a teológia és a vallástudomány szavakat, de nem teljesen tudod, mi a különbség köztük? Akkor itt a helyed! Előadásomban a fenti kérdésekről való beszélgetésen túl részletesen kitérek a "szentkönyves vallások" (zsidóság, kereszténység, iszlám, szikhizmus) előírásaira, tabuira - sőt, megkísérlem bemutatni, mi és miért történik egy zsinagógában, templomban, mecsetben vagy gurdvara-ban. (Az előadást - mint műfajt - nem kell szigorúan venni, minden felmerülő kérdést igyekszem majd megválaszolni, inkább beszélgetést tervezek, mint 90 perces monológot)','11','0','user','0','Czétényi Gellért tanár úr','30','2024-10-24 09:00:00','2024-10-24 09:45:00','2024-10-26 20:00:00',NULL,NULL,NULL,127),
('104','Fizikusok a gáton ','Bár mi nem pakolunk homokzsákokat, de szívesen elmeséljük mire jutottunk az árvíz jelenségének tanulmányozásában a tantáborban (Fizika előadás haladóknak, 10. évfolyamtól)','11','0','user','0','Csorba Vendel - Demján Gergely - Mayer Máté - Muszev Nikola (mind: 12. C) - Sas Tamás tanár úr (volt E5vös-diák)','30','2024-10-24 09:00:00','2024-10-24 09:45:00','2024-10-27 20:00:00',NULL,NULL,NULL,128),
('105','Az orvosi megismerés módszertana','Manapság nem kell orvosnak lenni, hogy csak úgy ömöljenek ránk az egészségügyi információk, hírek, amik tengerében nem könnyű eligazodni. Okoz rákot a mobiltelefon? Véd a rák ellen az új vitamin? Működik ez az új oltás? (Egyáltalán, mit jelent az, hogy működik?) Előadásomban megpróbálom azokat a legfontosabb módszereket megmutatni, amelyekkel ilyen és ezekhez hasonló kérdésekre próbálnak válaszolni a kutatók. Különös hangsúllyal térek ki a tipikus félreértésekre, félrevezetésekre, csapdákra (amikből van bőven!) (9. évfolyamtól ajánlott)','11','0','user','0','Dr. Ferenci Tamás biostatisztikus, orvosbiológiai mérnök, egyetemi docens (BCE)','30','2024-10-24 09:00:00','2024-10-24 09:45:00','2024-10-28 20:00:00',NULL,NULL,NULL,NULL),
('106','"Így jöttem én" - egy rendezői / alkotói identitás alakulása','Fodor Orsolya (1994) jelenleg Budapesten élő és alkotó színházcsináló. Szabadúszó (báb)rendezői, dramaturgiai munkái mellett különféle non-hierarchikus együttműködésekben alkot. A szerzőiség, az alkotás kollektív formái, ezek egymásra hatása érdeklik. Fő kutatási területe a performatív beavatkozások hatása a tér szakrális nyelvére. Saját munkássága bemutatásán keresztül a hazai független színházi / előadóművészeti szféra helyzetére is rálátást enged (15-16 éves kor felett ajánlott)','11','0','user','0','Fodor Orsolya bábrendező, előadó, PhD-hallgató (Freeszfe Egyesület, Képzőműv. Egy., volt E5vös-diák)','30','2024-10-24 09:00:00','2024-10-24 09:45:00','2024-10-29 20:00:00',NULL,NULL,NULL,NULL),
('107','A szavak erdejében ','A tagolt, emberi nyelv mint kommunikációs eszköz nem létezhet szavak nélkül. A szavak segítségével alkotjuk meg mondatainkat, de ezen túlmenően azért is fontos „alkatrészei” a nyelvnek, mert segítségükkel nevezzük meg a minket körülvevő világ elemeit, amelyek egyben az általuk hordozott műveltséget is tükrözik. Előadásom első részében a magyar szókészletet alkotó szavak eredetbeli vonatkozásaival foglalkozom (vázlatosan): milyen eredetű például a kéz, az alma, a parancsol, a pék, a tábla, a könyv, a garázs; és vajon miért éppen olyan eredetűek. Előadásom második felének témája pedig az idegen szavak „létjogosultságának” rendszeresen felbukkanó kérdése: mit kezdjünk, kezdhetünk az olyan szavakkal, mint lime, workshop, hashtag, podcast és társaik','11','0','user','0','Dr. Gerstner Károly nyelvész, tudományos főmunkatárs (HUN-REN Nyelvtud. Kut.közp., volt E5vös-diák)','30','2024-10-24 09:00:00','2024-10-24 09:45:00','2024-10-30 20:00:00',NULL,NULL,NULL,130),
('108','eu-LISA, a schengeni rendszer digitális szíve','Áttekintést nyújtok az európai uniós karrierekről, lehetőségekről, bemutatva egy fiatal ügynökség életét és munkáját. Ajánlom mindazoknak, akik gondolkodnak, hogy erre a karrierútra lépnek, és azoknak is, akiket érdekel, hogy mi biztosítja számukra a szabad utazást Európán belül, és mi segíti elő a biztonságukat. Az előadás során a prezentáció és néhány videó angol nyelven fog menni, de az előadás magyar nyelvű lesz','11','0','user','0','Gregus Vidor ügyintéző (Európai Bizottság, volt E5vös-diák)','30','2024-10-24 09:00:00','2024-10-24 09:45:00','2024-10-31 20:00:00',NULL,NULL,NULL,NULL),
('109','2D-s játékfejlesztés: Kreativitás, Kód és Kihívás','Merülj el a játékfejlesztés lenyűgöző világában! Csatlakozz egy interaktív utazásra, ahol egyszerű példák segítségével 2D-s játékokat fejlesztünk. Ismerd meg a játékok létrehozásának izgalmas lépéseit és kihívásait! (A teljes megértéshez ugyan segítség, ha valakinek vannak koordinátageometriai és programozási (c#) ismeretei, de a program úgy van összeállítva, hogy ennek hiányában is élvezhető)','11','0','user','0','Haydu Lénárt vezető szoftverfejlesztő, egyetemi oktató (evosoft Hungary Kft., Óbudai Egy. Neuman J. Inf. Kar)','30','2024-10-24 09:00:00','2024-10-24 09:45:00','2024-11-01 20:00:00',NULL,NULL,NULL,NULL),
('110','Az aranyszabálytól a megkövezésig - Filozófiai diskurzusok a viszonosságról ','A sajátosan emberinek gondolt tulajdonságokból egyre kevesebb „tartja magát” az állatvilágot vagy a mesterséges intelligenciát jellemző képességekkel szemben. (Közülük kiesett pl. az eszközhasználat, a kommunikáció vagy a nevetés.) Mai ismereteink szerint két képesség tartható jó eséllyel speciálisnak, csak az emberre jellemzőnek. Az egyik az öntudat: az ember képes tudatában lenni annak, hogy ember – hogy „milyen magának lenni”. A másik a belátás: az ember bele tudja képzelni magát egy másik ember helyébe – hogy „milyen másiknak lenni” –, és képes e képzeletbeli „helycserét” figyelembe véve ítélni tettéről, szándékáról, önképéről. Persze jócskán akadnak viták ennek lefolyásáról és szabályairól (egy-két ilyenről szól az előadás), de az vitathatatlan, hogy nem apróságok múlnak a belátás képességén: pl. empátia, tolerancia, szabadságtudat, önismeret','11','0','user','0','Dr. Hévizi Ottó filozófus, író, filozófiatörténész (HUN-REN Bölcsészettud. Kut.közp.)','30','2024-10-24 09:00:00','2024-10-24 09:45:00','2024-11-02 20:00:00',NULL,NULL,NULL,131),
('111','Mivel járult hozzá az "Arab Reneszánsz" az egyetemes kultúrához? ','Belső-Ázsia 800 és 1200 között a világ kulturális központja volt. Az itt felhalmozott tudás vegyülete volt a kínai, indiai, közel-keleti és a helyi kulturáknak, vallásoknak. Ez a termékeny elegy jutott el Európába, de vajon hogyan? Milyen újdonságot jelentett megjelenése a klasszikus ismeretekhez képest? (A 9-12. évfolyam diákjainak ajánlott)','11','0','user','0','Holicsné Csejk Gabriella tanárnő','30','2024-10-24 09:00:00','2024-10-24 09:45:00','2024-11-03 20:00:00',NULL,NULL,NULL,132),
('112','Zöld energiaátmeneti dilemmák - megoldások (biogáz, hidrogén)','Mennyi és milyen energiát használunk a világban? Lehetséges-e a fosszilis energiahordozók kiváltása? Milyen kihívásai, dilemmái vannak a zöld átmenetnek? Milyen szerepe lehet a zöldülésben például a biogáznak, vagy a zöld hidrogénnek? Mibe fektet a MOL, mint a régió meghatározó energetikai szereplője?','11','0','user','0','Horváth Ádám vezető (Új és Fenntartható üzletágak, MOL-csoport)','30','2024-10-24 09:00:00','2024-10-24 09:45:00','2024-11-04 20:00:00',NULL,NULL,NULL,NULL),
('113','A génszerkesztéstől a célzott terápiákig - a genetikai forradalom legizgalmasabb eredményei','Az utóbbi évtizedekben kifejlesztett technológiákkal a genom olvashatóvá és szerkeszthetővé vált, ami megváltoztatta az orvostudományt, a biológiai kutatásokat, de akár a származásunkat is megismerhetjük egy DNS-minta elküldésével. Az előadásomban szeretném részletezni néhány közismert, a genetikával kapcsolatos technológia működési elvét, és a tudományágban rejlő lehetőségeket és kihívásokat (A biológia és a kémia iránt érdeklődő, alapokkal már rendelkező diákok számára ajánlott!)','11','0','user','0','Kós Tamás bioinformatikus, rákkutató, PhD-hallgató (SE ÁOK, volt E5vös-diák)','30','2024-10-24 09:00:00','2024-10-24 09:45:00','2024-11-05 20:00:00',NULL,NULL,NULL,NULL),
('114','Mit csinál(hat) egy biológus?','Olyan 10-12. évfolyamba járó diákokra számítok a kötetlen beszélgetés során, akiket a biológia érdekel, de még nem tudják, merre folytassák a középiskola után: pl. környezet- és természetvédelem? növények és állatok terepi megfigyelése? fertőzések, betegségek okainak felderítése, esetleg megelőzése? génsebészet, génszerkesztés? az idegrendszer működésének megértése? Igyekszem bemutatni a választási lehetőségeket és azt, hogy a kutatói munka során milyen kihívásokkal - izgalmakkal és nehézségekkel - találkozhatunk','11','0','user','0','Dr. Schlett Katalin biológus, egyetemi docens (ELTE TTK)','30','2024-10-24 09:00:00','2024-10-24 09:45:00','2024-11-06 20:00:00',NULL,NULL,NULL,NULL),
('115','Képernyőm, képernyőm, mondd meg nékem, ki a legszebb e vidéken? ','A szépségipar mindig is erős befolyással bírt az önképünkre. Az interneten a közösségi média által mutatott tökéletes(nek tűnő) életek, és újabban a mesterséges intelligenciával generált képek is megnehezítik, hogy szépnek lássuk magunkat a mindennapokban. Ebben az interaktív foglalkozásban azt gyakoroljuk, hogy hogyan ismerjük fel és kezeljük jól azt a nagy nyomást, amit az interneten látott "tökéletes nő" képe vált ki belőlünk. Szeretettel várok mindenkit, aki érezte már úgy, hogy egy görgetéssel eltöltött óra után negatívabban látta önmagát. (Lányok jelentkezését várják alapvetően)','11','0','user','0','Seben Laura önkéntes (NANE Egyesület)','30','2024-10-24 09:00:00','2024-10-24 09:45:00','2024-11-07 20:00:00',NULL,NULL,NULL,138),
('116','Nincs királyi út? - Érdekességek a választási rendszerek világából ','Hogyan válasszunk mi választási rendszert? Bevezetés a kollektív döntéshozatal matematikájába (social choice), nem túl sok matematikával. Az egy győzteses választási rendszerek alapjai, a Condorcet-paradoxon, a taktikai szavazás és a stratégiai jelölés. (Az előadás előismereteket nem igényel. De interaktív, ezért mobiltelefon használata ajánlott!)','11','0','user','0','Stankovics Ábel egyetemi hallgató (ELTE ÁJK, volt E5vös-diák)','30','2024-10-24 09:00:00','2024-10-24 09:45:00','2024-11-08 20:00:00',NULL,NULL,NULL,139),
('117','Feladataink és lehetőségeink a gyorsuló változások korában ','Megújuló erőforrások túlhasználata, nem-megújuló erőforrások kimerülése, klímaváltozás, energiaválság, polikrízis. Az előadás bemutatja azokat a természeti és társadalmi folyamatokat, amelyek következtében életkörülményeink a közeljövőben lényegesen megváltoznak. A változások jelentős része még befolyásolható pozitív és negatív irányban is, azonban elkerülhetetlen, hogy ezekkel a változásokkal tisztában legyünk, és legjobb tudásunk és lehetőségünk szerint alkalmazkodjunk hozzájuk. Az alkalmazkodás aktív cselekvést jelent, mely csak akkor lehet sikeres, ha nem dugjuk homokba a fejünket, hanem bátran szembenézünk a tényekkel. A fiatal generációkra vár, hogy megértve a helyzet súlyosságát mielőbb megváltoztassák azokat a negatív társadalmi és gazdasági folyamatokat, amelyek a jelenlegi helyzethez vezettek. (Az előadásra az EPAS csapatának szervezésében kerül sor)','11','0','user','0','Szalóczy Zsolt fizikus, üzletember, vezérigazgató (Cassee Klímaadaptációs Tanácsadó Zrt.)','30','2024-10-24 09:00:00','2024-10-24 09:45:00','2024-11-09 20:00:00',NULL,NULL,NULL,140),
('118','Szúró- és vágófegyverek a filmvásznon és a valóságban ','Történelmi ("historikus-kardrahányós") filmekben bemutott fegyverek és használatuk kritikai jellemzése kétszer 45 percben. A második részben hiteles fegyvermásolatok (kardok, szablyák, tőrök) kézbevételére, felügyelt kipróbálására is lesz lehetőség','11','0','user','0','Szeiman József tanár úr (nem oly" rég az E5vösben) - Oszlánszky Gábor fegyvergyűjtő','30','2024-10-24 09:00:00','2024-10-24 09:45:00','2024-11-10 20:00:00',NULL,NULL,NULL,141),
('119','Az Európai Unió Zöld Programja és a fenntartható fejlődés','"A jövő zöld lesz, vagy nem lesz!" Esélyeink a globális klímaváltozás korában?','11','0','user','0','Tar Imre tanár úr','30','2024-10-24 09:00:00','2024-10-24 09:45:00','2024-11-11 20:00:00',NULL,NULL,NULL,NULL),
('120','“Szólj be a papnak” - fórum és közös gondolkozás mindenről, ami az élet ','“Szólj be a papnak!” - azaz gyere, és beszélgessünk! Nem tudjuk a tutit, de szívesen gondolkozunk együtt az életről, világról, a valóságról, és arról, ami azon túl van. Többféle felekezet lelkészével, rabbival lesz lehetőség találkozni, beszélgetni (Sokat segítetetek, ha a szervezők által megadott címre előre elkülditek a kérdéseiteket. Köszi!)','11','0','user','0','Dr. Thoma László református lelkipásztor – Harmai Gábor római katolikus lelkész – Szántó Enikő evangélikus lelkész református lelkipásztor','30','2024-10-24 09:00:00','2024-10-24 09:45:00','2024-11-12 20:00:00',NULL,NULL,NULL,142),
('121','Aki "A"-t mond, mondjon "Cs"-t is? - avagy meddig árad még a … Río Paraná?','Iskolánk legnagyobb világutazó történelem - földrajz tanára személyes élményei alapján most Dél-Amerika két legdélebbi országáról, Argentínáról és Chiléről mesél 45 percben','11','0','user','0','Tisza László nyugdíjas tanár (nem oly" rég még az E5vösben)','30','2024-10-24 09:00:00','2024-10-24 09:45:00','2024-11-13 20:00:00',NULL,NULL,NULL,NULL),
('122','Gyerekeknek szólnak-e a gyerekfilmek?','Mindenki sok mesefilmet látott. De vajon észrevetted-e, hogy az alkotók gyakran kikacsintottak a felnőttek felé is? Néhány példán keresztül megpróbáljuk felfedezni ezeket','11','0','user','0','Varga Sándor tanár úr (volt E5vös-diák)','30','2024-10-24 09:00:00','2024-10-24 09:45:00','2024-11-14 20:00:00',NULL,NULL,NULL,NULL),
('123','Nagyragadozók, menhely, felelős állattartás ','Egyedmentés a nagyragadozóknál. Menhelyi tartás nagykifutós körülmények között. Tények és tévhitek a vadállatokról','11','0','user','0','Zsiák Norbert üzemeltetési vezető (Medveotthon Veresegyház, volt E5vös-diák)','30','2024-10-24 09:00:00','2024-10-24 09:45:00','2024-11-15 20:00:00',NULL,NULL,NULL,147),
('124','Gépészmérnök: gép és ész és még sok minden','A gépészmérnöki szakmával kapcsolatban elsősorban a nehézgépipar jut eszünkbe, ami természetesen a szakma egy része, ám az előadás célja bemutatni a diáksággal, hogy a körülöttünk lévő világ számtalan folyamatát gépészmérnökök írányítják. Az épületek hőellátásában, a városi és országos energetikai folyamatokban, a vegyiparban, az élélmiszeriparban, a csomagolástechnikában és még számos egyéb területen mind gépészmérnökök gondoskodnak arról, hogy gyorsan, magas minőségen és energiahatékonyan - egyszóval optimalizálva gyártsunk, szolgáltassunk. Már ebből láthatjuk, hogy egy gépészmérnök folyamatosan problémamegoldó helyzetben van, amely - egy kis gyakorlat után - az egész gondolkozásmódját analitikussá és optimumkeresővé formálja','12','0','user','0','Dr. Bokor Balázs gépészmérnök, adjunktus (BME Gépészmérnöki Kar)','30','2024-10-24 10:00:00','2024-10-24 10:45:00','2024-11-16 20:00:00',NULL,NULL,NULL,NULL),
('125','Mindent a (kész)pénzről ','A hagyományos pénzektől az előadás során eljutunk a modern elektronikus pénzekig, és az elektronikus fizetésig. A tudásotokra, ismereteitekre és a véleményetekre is szükség lesz a játékok alatt','12','0','user','0','Dr. Bódi-Schubert Anikó közgazdász, főosztályvezető (Magyar Nemzeti Bank)','30','2024-10-24 10:00:00','2024-10-24 10:45:00','2024-11-17 20:00:00',NULL,NULL,101,NULL),
('126','(Hogyan ne legyél) idiótákkal körülvéve? - A DISC rendszer személyiségtípusai ','Thomas Erikson "Idiótákkal körülvéve" című könyvében leírt DISC személyiségtípusokról fogok beszélni. Hogyan kell viszonyulni bizonyos embertípusokhoz? Hogyan lehet megérteni azokat az embereket, akiknek számodra értelmezhetetlenek a gondolatmenetei? Hogyan lehet jó csapatot építeni belőlük? Milyen egy jó csapat? Beszélek önismeretről is, hogyan használjuk személységtípusaink erősségeit, és hogyan javítsunk a gyengébb részein','12','0','user','0','Czakó Anna (11. E)','30','2024-10-24 10:00:00','2024-10-24 10:45:00','2024-11-18 20:00:00',NULL,NULL,102,NULL),
('127','Mi fán terem a vallás? ','Gondolkodtál már azon, hogy mi is az a "vallás"? Mire jó? Miért hisz több milliárd ember valami(k)ben, ami(k)re semmi bizonyítéka nincs? Érdekel, mitől lesz valami "szent", vagy épp fordítva, mitől lesz profánná? Sokszor hallod a teológia és a vallástudomány szavakat, de nem teljesen tudod, mi a különbség köztük? Akkor itt a helyed! Előadásomban a fenti kérdésekről való beszélgetésen túl részletesen kitérek a "szentkönyves vallások" (zsidóság, kereszténység, iszlám, szikhizmus) előírásaira, tabuira - sőt, megkísérlem bemutatni, mi és miért történik egy zsinagógában, templomban, mecsetben vagy gurdvara-ban. (Az előadást - mint műfajt - nem kell szigorúan venni, minden felmerülő kérdést igyekszem majd megválaszolni, inkább beszélgetést tervezek, mint 90 perces monológot)','12','0','user','0','Czétényi Gellért tanár úr','30','2024-10-24 10:00:00','2024-10-24 10:45:00','2024-11-19 20:00:00',NULL,NULL,103,NULL),
('128','Fizikusok a gáton ','Bár mi nem pakolunk homokzsákokat, de szívesen elmeséljük mire jutottunk az árvíz jelenségének tanulmányozásában a tantáborban (Fizika előadás haladóknak, 10. évfolyamtól)','12','0','user','0','Csorba Vendel - Demján Gergely - Mayer Máté - Muszev Nikola (mind: 12. C) - Sas Tamás tanár úr (volt E5vös-diák)','30','2024-10-24 10:00:00','2024-10-24 10:45:00','2024-11-20 20:00:00',NULL,NULL,104,NULL),
('129','Beszélgessünk nyíltan a rasszizmusról!','Akármilyen korúak is vagyunk, mindannyian találkozunk társadalmi problémákkal a mindennapjainkban. A rasszizmus is ezek közé tartozik, mégis, gyakran nincs megfelelő alkalom arra, hogy őszintén és nyíltan beszélgessünk róla. Előadásunk keretében egy interaktív beszélgetésre hívunk titeket, hogy párbeszédet indítsunk arról, hogy mit jelent a rasszizmus a különböző közösségek és egyének életében, és hogyan küzdhetünk ellene','12','0','user','0','Az Eötvös MUN-Club vezetősége','20','2024-10-24 10:00:00','2024-10-24 10:45:00','2024-11-21 20:00:00',NULL,NULL,NULL,NULL),
('130','A szavak erdejében ','A tagolt, emberi nyelv mint kommunikációs eszköz nem létezhet szavak nélkül. A szavak segítségével alkotjuk meg mondatainkat, de ezen túlmenően azért is fontos „alkatrészei” a nyelvnek, mert segítségükkel nevezzük meg a minket körülvevő világ elemeit, amelyek egyben az általuk hordozott műveltséget is tükrözik. Előadásom első részében a magyar szókészletet alkotó szavak eredetbeli vonatkozásaival foglalkozom (vázlatosan): milyen eredetű például a kéz, az alma, a parancsol, a pék, a tábla, a könyv, a garázs; és vajon miért éppen olyan eredetűek. Előadásom második felének témája pedig az idegen szavak „létjogosultságának” rendszeresen felbukkanó kérdése: mit kezdjünk, kezdhetünk az olyan szavakkal, mint lime, workshop, hashtag, podcast és társaik','12','0','user','0','Dr. Gerstner Károly nyelvész, tudományos főmunkatárs (HUN-REN Nyelvtud. Kut.közp., volt E5vös-diák)','30','2024-10-24 10:00:00','2024-10-24 10:45:00','2024-11-22 20:00:00',NULL,NULL,107,NULL),
('131','Az aranyszabálytól a megkövezésig - Filozófiai diskurzusok a viszonosságról ','A sajátosan emberinek gondolt tulajdonságokból egyre kevesebb „tartja magát” az állatvilágot vagy a mesterséges intelligenciát jellemző képességekkel szemben. (Közülük kiesett pl. az eszközhasználat, a kommunikáció vagy a nevetés.) Mai ismereteink szerint két képesség tartható jó eséllyel speciálisnak, csak az emberre jellemzőnek. Az egyik az öntudat: az ember képes tudatában lenni annak, hogy ember – hogy „milyen magának lenni”. A másik a belátás: az ember bele tudja képzelni magát egy másik ember helyébe – hogy „milyen másiknak lenni” –, és képes e képzeletbeli „helycserét” figyelembe véve ítélni tettéről, szándékáról, önképéről. Persze jócskán akadnak viták ennek lefolyásáról és szabályairól (egy-két ilyenről szól az előadás), de az vitathatatlan, hogy nem apróságok múlnak a belátás képességén: pl. empátia, tolerancia, szabadságtudat, önismeret','12','0','user','0','Dr. Hévizi Ottó filozófus, író, filozófiatörténész (HUN-REN Bölcsészettud. Kut.közp.)','30','2024-10-24 10:00:00','2024-10-24 10:45:00','2024-11-23 20:00:00',NULL,NULL,110,NULL),
('132','Mivel járult hozzá az "Arab Reneszánsz" az egyetemes kultúrához? ','Belső-Ázsia 800 és 1200 között a világ kulturális központja volt. Az itt felhalmozott tudás vegyülete volt a kínai, indiai, közel-keleti és a helyi kulturáknak, vallásoknak. Ez a termékeny elegy jutott el Európába, de vajon hogyan? Milyen újdonságot jelentett megjelenése a klasszikus ismeretekhez képest? (A 9-12. évfolyam diákjainak ajánlott)','12','0','user','0','Holicsné Csejk Gabriella tanárnő','30','2024-10-24 10:00:00','2024-10-24 10:45:00','2024-11-24 20:00:00',NULL,NULL,111,NULL),
('133','Repülés és informatika','A repülés és a légiközlekedés ma már elképzelhetetlen fejlett informatikai háttér nélkül. Ha érdekel a repülés csodálatos világa és szeretnél ilyen területen dolgozni, gyere és tudd meg: hogyan vált a Lufthansa Európa legnagyobb és legbiztonságosabb légitársaságává? És hogyan lett a Lufthansa Systems a világ legjobb repülési informatikai rendszereit fejlesztő vállalata? Mesélek majd repülőgépekről, repterekről, a jelen és a jövő IT-megoldásairól','12','0','user','0','Kenessey László légiközlekedési informatikus (Lufthansa Systems Hungária)','30','2024-10-24 10:00:00','2024-10-24 10:45:00','2024-11-25 20:00:00',NULL,NULL,NULL,NULL),
('134','Apám levelei','Apám, Kis György textiltechnológus 1942. május 1-jén bevonult munkaszolgálatra, melyet a Don-kanyarban töltött. Nem jött vissza. Mintegy 50 tábori levelezőlapot küldött édesanyámnak. Ezekből szerkesztettem egy kötetet, melynek megjelenése után volt alkalmam megismerni apám történetének néhány korábban nem ismert vonatkozását. Meglátogattam a helyszínt is. Feldolgoztam apám hagyatékának egy másik darabját is, amely alkalmat ad annak megismerésére, hogyan látta egy zsidó polgár a háború előtti években a világot','12','0','user','0','Dr. Kis Ádám könyvkiadó (SZAK Kiadó, volt E5vös-diák)','30','2024-10-24 10:00:00','2024-10-24 10:45:00','2024-11-26 20:00:00',NULL,NULL,NULL,NULL),
('135','Te is lehetsz cserediák! Latin-amerikai élménybeszámoló','Érdekel egy másik világ? Kíváncsi vagy, hogyan élnek a földgömb másik felén? Milyen ebbe a világba magyar diákként belecsöppenni? Akkor gyere és hallgasd meg az előadásomat Argentínáról és Mexikóról, ahol cserediák voltam. Az előadásomban sorra veszem az eseményeket az elhatározástól a hazatérésemig, ami hasznos lehet számodra, ha Te is szeretnél cserediák lenni','12','0','user','0','Máté Nóra (11. F)','30','2024-10-24 10:00:00','2024-10-24 10:45:00','2024-11-27 20:00:00',NULL,NULL,NULL,NULL),
('136','Egy informatikus mindennapjai','Hogyan telnek egy informatikus mindennapjai, milyen kihívásokkal kell naponta szembenéznie? Milyen nehézségekkel találkozik, és mik a munkája szépségei?','12','0','user','0','Nagy Ákos informatikus (volt E5vös-diák)','30','2024-10-24 10:00:00','2024-10-24 10:45:00','2024-11-28 20:00:00',NULL,NULL,NULL,NULL),
('137','Létezik-e demokrácia? Dilemmák a közösségi döntéshozatalban','Létezik-e valódi demokratikus döntéshozatal? Egyáltalán hogyan döntünk közösségi kérdésekben? Miként tudjuk összesíteni az egyéni döntéseket? Ilyen, és ehhez hasonló kérdésekre keressük majd a választ komoly, de mégis játékos formában (egy interaktív játék során telefon használata szükséges)','12','0','user','0','Őrsi Marcell egyetemi hallgató (Bud. Metropolitan Egy., volt E5vös-diák)','30','2024-10-24 10:00:00','2024-10-24 10:45:00','2024-11-29 20:00:00',NULL,NULL,NULL,NULL),
('138','Képernyőm, képernyőm, mondd meg nékem, ki a legszebb e vidéken? ','A szépségipar mindig is erős befolyással bírt az önképünkre. Az interneten a közösségi média által mutatott tökéletes(nek tűnő) életek, és újabban a mesterséges intelligenciával generált képek is megnehezítik, hogy szépnek lássuk magunkat a mindennapokban. Ebben az interaktív foglalkozásban azt gyakoroljuk, hogy hogyan ismerjük fel és kezeljük jól azt a nagy nyomást, amit az interneten látott "tökéletes nő" képe vált ki belőlünk. Szeretettel várok mindenkit, aki érezte már úgy, hogy egy görgetéssel eltöltött óra után negatívabban látta önmagát. (Lányok jelentkezését várják alapvetően)','12','0','user','0','Seben Laura önkéntes (NANE Egyesület)','30','2024-10-24 10:00:00','2024-10-24 10:45:00','2024-11-30 20:00:00',NULL,NULL,115,NULL),
('139','Nincs királyi út? - Érdekességek a választási rendszerek világából ','Hogyan válasszunk mi választási rendszert? Bevezetés a kollektív döntéshozatal matematikájába (social choice), nem túl sok matematikával. Az egy győzteses választási rendszerek alapjai, a Condorcet-paradoxon, a taktikai szavazás és a stratégiai jelölés. (Az előadás előismereteket nem igényel. De interaktív, ezért mobiltelefon használata ajánlott!)','12','0','user','0','Stankovics Ábel egyetemi hallgató (ELTE ÁJK, volt E5vös-diák)','30','2024-10-24 10:00:00','2024-10-24 10:45:00','2024-12-01 20:00:00',NULL,NULL,116,NULL),
('140','Feladataink és lehetőségeink a gyorsuló változások korában ','Megújuló erőforrások túlhasználata, nem-megújuló erőforrások kimerülése, klímaváltozás, energiaválság, polikrízis. Az előadás bemutatja azokat a természeti és társadalmi folyamatokat, amelyek következtében életkörülményeink a közeljövőben lényegesen megváltoznak. A változások jelentős része még befolyásolható pozitív és negatív irányban is, azonban elkerülhetetlen, hogy ezekkel a változásokkal tisztában legyünk, és legjobb tudásunk és lehetőségünk szerint alkalmazkodjunk hozzájuk. Az alkalmazkodás aktív cselekvést jelent, mely csak akkor lehet sikeres, ha nem dugjuk homokba a fejünket, hanem bátran szembenézünk a tényekkel. A fiatal generációkra vár, hogy megértve a helyzet súlyosságát mielőbb megváltoztassák azokat a negatív társadalmi és gazdasági folyamatokat, amelyek a jelenlegi helyzethez vezettek. (Az előadásra az EPAS csapatának szervezésében kerül sor)','12','0','user','0','Szalóczy Zsolt fizikus, üzletember, vezérigazgató (Cassee Klímaadaptációs Tanácsadó Zrt.)','30','2024-10-24 10:00:00','2024-10-24 10:45:00','2024-12-02 20:00:00',NULL,NULL,117,NULL),
('141','Szúró- és vágófegyverek a filmvásznon és a valóságban ','Történelmi ("historikus-kardrahányós") filmekben bemutott fegyverek és használatuk kritikai jellemzése kétszer 45 percben. A második részben hiteles fegyvermásolatok (kardok, szablyák, tőrök) kézbevételére, felügyelt kipróbálására is lesz lehetőség','12','0','user','0','Szeiman József tanár úr (nem oly" rég az E5vösben) - Oszlánszky Gábor fegyvergyűjtő','30','2024-10-24 10:00:00','2024-10-24 10:45:00','2024-12-03 20:00:00',NULL,NULL,118,NULL),
('142','“Szólj be a papnak” - fórum és közös gondolkozás mindenről, ami az élet ','“Szólj be a papnak!” - azaz gyere, és beszélgessünk! Nem tudjuk a tutit, de szívesen gondolkozunk együtt az életről, világról, a valóságról, és arról, ami azon túl van. Többféle felekezet lelkészével, rabbival lesz lehetőség találkozni, beszélgetni (Sokat segítetetek, ha a szervezők által megadott címre előre elkülditek a kérdéseiteket. Köszi!)','12','0','user','0','Dr. Thoma László református lelkipásztor – Harmai Gábor római katolikus lelkész – Szántó Enikő evangélikus lelkész református lelkipásztor','30','2024-10-24 10:00:00','2024-10-24 10:45:00','2024-12-04 20:00:00',NULL,NULL,120,NULL),
('143','El tudja az emberiség kerülni a klímakatasztrófát?','"Már túl késő! Nincs esély az éghajlatváltozás megállítására" "A civilizációs összeomlás elkerülhetetlen" és hasonló hangulatú címekkel van ellepve a média, emellett napi szinten olvasunk különféle katasztrófákról, amit az éghajlatváltozás okozott. Az emberek túlnyomó része elvesztette a reményét az éghajlatváltozás megoldásával kapcsolatban, sokakat szorongás is érint emiatt. Az előadásban arról lesz szó, hogy van-e még lehetőség tenni valamit, hogy élhető jövő elé nézzünk, vagy tényleg elkéstünk ezzel','12','0','user','0','Ürge Boróka egyetemi hallgató, Magyarország ifjúsági klímaküldöttje (ENSZ éghajlatváltozási keretegyezménye)','30','2024-10-24 10:00:00','2024-10-24 10:45:00','2024-12-05 20:00:00',NULL,NULL,NULL,NULL),
('144','A Budapesti Műszaki és Gazdaságtudományi Egyetem és az építészmérnöki képzése','Az építészmérnöki képzéshez kapcsolódó szakmák, karrierutak és kutatások','12','0','user','0','Varga Imre városgazdász, építőmérnök, mérnöktanár (BME Építészmérnöki Kar) - Hegedűs Benedek Bence egyetemi hallgató (BME ÉK, volt E5vös-diák)','30','2024-10-24 10:00:00','2024-10-24 10:45:00','2024-12-06 20:00:00',NULL,NULL,NULL,NULL),
('145','Diktátorok hajnala','Diktátorok voltak, vannak és lesznek. Vajon a múlt tanulmányozása alapján látható-e valamilyen szükségszerűség a bukásukban? Meg tudjuk-e jósolni, mi vezet el odáig? Mi most megpróbáljuk','12','0','user','0','Varga Sándor tanár úr (volt E5vös-diák)','30','2024-10-24 10:00:00','2024-10-24 10:45:00','2024-12-07 20:00:00',NULL,NULL,NULL,NULL),
('146','Nyelv, Kultúra, Gondolkodás - Hogyan befolyásolja a különböző népek nyelvhasználata a világnézetüket?','Elgondolkoztál már azon, hogy milyen összefüggés lehet a latin diēs ("nap") és Zeusz neve között? Érdekel, miért írtak a görögök és a sumérok jobbra-balra váltakozó irányban a kőtábláikra? Ötleted sincs, hogy egyes bennszülött törzsek számára mit jelent a "hangyászorr", a "banánlevél" vagy a "kézanya" fogalmak? Szívesen rácsodálkoznál az emberi gondolkodás sokszínűségére? Ha bármelyik (vagy éppen egyik sem) igaz rád ezek közül, itt a helyed!','12','0','user','0','Virág Máté Gergely (12. C)','30','2024-10-24 10:00:00','2024-10-24 10:45:00','2024-12-08 20:00:00',NULL,NULL,NULL,NULL),
('147','Nagyragadozók, menhely, felelős állattartás ','Egyedmentés a nagyragadozóknál. Menhelyi tartás nagykifutós körülmények között. Tények és tévhitek a vadállatokról','12','0','user','0','Zsiák Norbert üzemeltetési vezető (Medveotthon Veresegyház, volt E5vös-diák)','30','2024-10-24 10:00:00','2024-10-24 10:45:00','2024-12-09 20:00:00',NULL,NULL,123,NULL),
('148','Miről ugatnak a kutyák? ','Vajon megérthető-e számunkra a kutyák vokalizációja? Milyen jelentése van az ugatásnak?','12','0','user','0','Dr. Faragó Tamás (ELTE Etológia Tanszék tudományos főmunkatársa)','30','2024-10-24 10:00:00','2024-10-24 10:45:00','2024-12-10 20:00:00',NULL,NULL,NULL,NULL),
('149','Világűr és műholdazás középiskolában','Rövid áttekintés a bekapcsolódási lehetőségekről a magyar űrtevékenységek terén, beleértve versenyeket, programokat, rendezvényeket és közösségeket. A látogatók első kézből megtekinthetik egy diákműhold bemutatóját, ami izgalmas betekintést nyújt a műholdépítés világába','21','0','user','0','Árok Péter
(Magyar Asztronautikai Társaság, Asztronautikai Diákklub)','23','2024-10-25 09:00:00','2024-10-25 10:00:00','2024-12-11 20:00:00',NULL,NULL,NULL,NULL),
('150','Kockázatelemzés egy befektetési bankban','Az előadás bemutatna a Morgan Stanley kockázatelemző részlegét, pár érdekességet, funkciót, karriereket, kapcsolatot a piaccal. Felsőbb éves diákoknak ajánlott, akik már közelebb vannak az egyetemválasztáshoz, és már egy kicsit több matematikát tanultak','21','0','user','0','Dr. Balázsi László
közgazdász (Morgan Stanley, volt E5vös-diák)','23','2024-10-25 09:00:00','2024-10-25 10:00:00','2024-12-12 20:00:00',NULL,NULL,NULL,NULL),
('151','A jövő technológiái','1800-ban a leggazdagabbak élete nem sokban különbözött attól, ahogyan egy római patrícius élt kétezer évvel korábban. A technológiai fejlődés a történelem során nem egyenletes: szinte minden, ami a mai életünket meghatározza, az elmúlt 200 évben jött létre. Mit tartogat a jövő? Gyorsul-e tovább a technológiai változás? Honnan lehet felismerni a jövő technológiáit még azelőtt, hogy megjelennének?','21','0','user','0','Dobos Gábor
jövőkutató, a Prométheusz Társaság vezetője (volt E5vös-diák)','23','2024-10-25 09:00:00','2024-10-25 10:00:00','2024-12-13 20:00:00',NULL,NULL,NULL,NULL),
('152','Nem úgy nőttem fel, hogy online csalások megelőzésével akarok foglalkozni','Először ügyvéd akartam lenni, aztán közgazdász, de rájöttem, hogy egyikben se teljesítettem volna jól. Most sem akarom életem végéig csinálni, de a csalásmegelőzés egy nagyon érdekes és hasznos dolog, szerintem. Ebben a mondatban a ""szerintem"" a kulcs: ha nem tudod mi legyél ha nagy leszel, keress valamit, ami fontos neked!','21','0','user','0','Fábián Gida
termékmenedzser (SEON Védelem banki csalás és pénzmosás ellen, volt E5vös-diák)','23','2024-10-25 09:00:00','2024-10-25 10:00:00','2024-12-14 20:00:00',NULL,NULL,NULL,NULL),
('153','Hogyan legyek karmester?','Itt a vissza nem térő alkalom: lerántjuk a leplet a karmester szakma minden csínjáról-bínjáról! Miért kell egyáltalán karmester, mire jó a pálca, mit figyel a brácsás és mit a triangulumos, ki a jó karmester, merre kell lengetni, mik a titkos jelek, miért nem szeretik a zenészek a karmestert, és miért szeretik? A karmesterséghez azonban nemcsak zenei, hanem vezetői ismeretek is szükségesek, hiszen egy szimfonikus zenekar nagyon hasonlóan működik egy vállalathoz. A karmester hibái, rossz döntései káoszt okozhatnak, de a jó karmester a tempót és a hangerőt irányító főnökből valódi vezetővé válhat, ha instrukcióival és jelenlétével képes a sokféle, hierarchizált rend szerint működő, magasan képzett hangszerest meggyőzni koncepciója helyességéről','21','0','user','0','Hámori Máté
karmester, a Danubia Zenekar művészeti vezetője','23','2024-10-25 09:00:00','2024-10-25 10:00:00','2024-12-15 20:00:00',NULL,NULL,NULL,NULL),
('154','Mi vár az EU-ra a következő években?','Geopolitikai verseny, klímaváltozás elleni harc, belső kihívások - interaktív közös gondolkodás az EU jövőjéről az új politikai ciklus kezdetén. Különösen hasznos és érdekes lehet a politika, nemzetközi kapcsolatok iránt érdeklődőknek, de bárkit szívesen látok az előadáson. Előzetes tudást az EU-ról nem igényel az előadás','21','0','user','0','Hóka Iván
politikai elemző (Európai Bizottság, volt E5vös-diák)','23','2024-10-25 09:00:00','2024-10-25 10:00:00','2024-12-16 20:00:00',NULL,NULL,NULL,NULL),
('155','Mindegy merre, csak előre!','Jávor Dani gyerekszínészként kezdte a munkát, Sas tanár úr táboraiban folytatta, volt videótékás, pr-es, a BMW kommunikációs vezetője, a MINI igazgatója, a Fesztiválzenekar marketingvezetője, a MOME üzletfejlesztési vezetője, most pedig HR-esnek tanul. Vallja, hogy ha nem vagy biztos benne, merre indulj, ne izgulj ezen, mert mindegy - bárhol is dolgozol majd, olyan gyakorlati tapasztalatokat szerzel, amivel közelebb jutsz ahhoz, amit igazán szeretnél. Még ha ezt közben nem is veszed észre...','21','0','user','0','Jávor Dániel
üzletfejlesztési vezető, Moholy-Nagy Művészeti Egyetem (volt E5vös-diák)','23','2024-10-25 09:00:00','2024-10-25 10:00:00','2024-12-17 20:00:00',NULL,NULL,NULL,NULL),
('156','Légiirányítás Magyarország fölött','A HungaroControl léginavigációs szolgáltatásokat nyújt a teljes magyar, illetve a koszovói magas légtérben közlekedő légi járművek számára. Tevékenységi körébe tartozik a légiforgalmi irányítók képzése is. A kétéves tanfolyam elvégzésével a hallgatók megszerzik a szakszolgálati engedélyüket. Az ideális jelölt kiválóan kommunikál, kiegyensúlyozott, felelősségteljes, gyorsan hoz hatékony döntést, csapatjátékos és képes huzamosabb ideig megosztani a figyelmét.
Látogatásunk célja, hogy népszerűsítsük a diákok körében ezt az egyedülálló és izgalmas hivatást. Fontosnak tartjuk a valósághű és hiteles bemutatkozást, ezért a jelenlévők az egyik légiforgalmi irányító kollégánktól első kézből értesülhetnek majd a szakma kulisszatitkairól. Az előadást követően kollégánk szívesen válaszol a légiforgalmi irányítással, a képzéssel és a kiválasztási folyamattal kapcsolatban felmerülő kérdésekre','21','0','user','0','Kelemen Szilvia
(HungaroControl)','23','2024-10-25 09:00:00','2024-10-25 10:00:00','2024-12-18 20:00:00',NULL,NULL,NULL,NULL),
('157','Programozni bárki tud','Bemutatom, hogyan lettem szoftverfejlesztő pénzügyi háttérrel, és hogy milyen készségekkel lehet érvényesülni ebben a szakmában. Előadásom betekintést nyújt a programozás alapjaiba, illetve kitérek arra is, hogy a mesterséges intelligencia tényleg elveszi-e a munkánkat','21','0','user','0','Kis Márton Bertalan
közgazdász, szoftvermérnök (volt E5vös-diák)','23','2024-10-25 09:00:00','2024-10-25 10:00:00','2024-12-19 20:00:00',NULL,NULL,NULL,NULL),
('158','Pályaválasztás Extremisztánban','Egy gazdasági elméletbe csomagolt pályaorientáció: a szürke és fekete hattyúk időszakában, ahol a bolygónkon már szinte minden mindennel összefügg, az átlagos eseményeket felváltják az extremitások. Egy ilyen világban felértékelődik a hibázás kultúrája és a tanulás képessége','21','0','user','0','Lendvai Viktor
közgazdász, a Hischool Alapítvány alapítója','23','2024-10-25 09:00:00','2024-10-25 10:00:00','2024-12-20 20:00:00',NULL,NULL,NULL,NULL),
('159','Legyen egy múzeum menő! Avagy hogyan lesz egy belsőépítészből kiállítási tartalomfejlesztő (is)','Ki is az a belsőépítész? Hol lehet ilyet tanulni? Hogyan lesz egy múzeumi kiállítás menő? Egy nem átlagos művészi életút a műemlékek világától a Budai palota kiállításának tervezéséig. Ez az előadás Neked szól, ha unod a múzeumokat, ha érdekel az építészet, vagy nem tudod, meg lehet- e élni szabadúszó művészként','21','0','user','0','Dr. Lukács Zsófia DLA
belsőépítész, építész tervezőművész, enteriőr történet-kutató','23','2024-10-25 09:00:00','2024-10-25 10:00:00','2024-12-21 20:00:00',NULL,NULL,NULL,NULL),
('160','A bírói hivatás','Az emberek általában kevés információval és meglehetősen egysíkú tudással rendelkeznek a bíróságok működéséről, a bírói munkáról, a bírói döntésekhez vezető útról. Bíróként is nap mint nap találkozom számos ilyen kérdéssel, például: Egyáltalán mivel foglalkoznak a bíróságok? Miért kell, hogy a bíróságok függetlenek legyenek? Miért húzódnak el az ügyek? Mit csinál egy bíró egész nap? Hogyan lehetne egy bíró pártatlan? Mi a különbség a bíró meg az ügyvéd között? Nálunk is van esküdtszék? Miért védekezik valaki szabadlábon? Ezekre keressük a választ, miközben azt is szeretném bemutatni, hogyan lesz valakiből bíró','21','0','user','0','Dr. Madarasi Anna
bíró (Fővárosi Törvényszék),
elnökségi tag (Res Iudicata Egyesület, volt E5vös-diák)','23','2024-10-25 09:00:00','2024-10-25 10:00:00','2024-12-22 20:00:00',NULL,NULL,NULL,NULL),
('161','Karrierlehetőségek egy multinál - határ a csillagos ég!','Karrier az olajipar egyik legnagyobb multinacionális vállalatában. Hogyan kerültem a Shell-hez, milyen karrierutat jártam be, mire volt ezekhez szükségem? Pályakép humorral és öniróniával','21','0','user','0','Marik Gyula
gazdasági szakember
(Shell Hungária Zrt.)','23','2024-10-25 09:00:00','2024-10-25 10:00:00','2024-12-23 20:00:00',NULL,NULL,NULL,NULL),
('162','Egy - remélhetőleg nem olyan unalmas - előadás az orvosi informatika világából','Markovics Dániel vagyok, lassan 20 éve az orvosi informatika területén dolgozok. Ez csak első olvasatra hangzik unalmasnak. Az orvosi informatika igazából egy végtelenül izgalmas, szerteágazó terület, ahol sokan megtalálhatják a számításaikat. Bemutatom, hogy én hogyan érkeztem a területre, mivel foglalkozunk, és arról is szeretnék nyíltan beszélni, hogy milyen árnyoldalai vannak ennek a világnak. Az előadásommal igyekszek majd megfelelni a hallgatóság vibe-jának, akár interakciókkal, de ha igény van rá, írathatok röpdolgozatot is a végén','21','0','user','0','Markovics Dániel
orvosi informatikus, mérnök (Varian Magyarország)','23','2024-10-25 09:00:00','2024-10-25 10:00:00','2024-12-24 20:00:00',NULL,NULL,NULL,NULL),
('163','Ne csak nézd! - Részvételi és közösségi színház','Milyen az az előadás, amiben a nézők is az előadás résztvevőivé, az események alakítóivá válhatnak? És milyen az, amit hétköznapi emberekkel közösen hoznak létre, akik saját történeteiket mondják el a színpadon? A közös alkalmunk során megismerkedhettek ezekkel a színházi műfajokkal, és bepillantást nyerhettek abba, hogyan épül fel egy ilyen alkotófolyamat. Rövid ismertető és inspiráló példák után játékos formában közösen gondolkodunk arról, hogy a titeket foglalkoztató témákat hogyan lehetne feldolgozni ezekkel az eszközökkel.
Milovits Hanna vagyok, 2021-ben végeztem a Színház- és Filmművészeti Egyetem drámainstrukor BA szakán, jelenleg az Örkény István Színházban dolgozom. Munkám során hasonló előadások létrehozásában veszek részt.','21','0','user','0','Milovits Hanna
drámainstruktor, színházi szakember
(Örkény István Színház, volt E5vös-diák)','23','2024-10-25 09:00:00','2024-10-25 10:00:00','2024-12-25 20:00:00',NULL,NULL,NULL,NULL),
('164','A kertásástól az építészeti nívódíjas irodaházi zöldfelületekig','Egykori iskolatársunk az egyetem mellett kezdett bele vállalkozásába, a Kisvakond nevű kertépítő cégbe. Mesél a kezdetekről, a növekedés lehetőségeiről, a sikeres vállalkozás kihívásairól','21','0','user','0','Nagy Csanád
tulajdonos (Kisvakond Zöldépítő Zrt., volt E5vös-diák)','23','2024-10-25 09:00:00','2024-10-25 10:00:00','2024-12-26 20:00:00',NULL,NULL,NULL,NULL),
('165','Nem közgazdásznak lenni','A közgazdász szakma iránt érdeklődőknek','21','0','user','0','Nagy János
makrogazdasági elemző (ERSTE, volt E5vös-diák)','23','2024-10-25 09:00:00','2024-10-25 10:00:00','2024-12-27 20:00:00',NULL,NULL,NULL,NULL),
('166','Hogyan építhetünk jó levegőjű városokat?','Városaink levegőminőségét a szennyezőanyag-kibocsátások és a város átszellőzési képességének egyensúlya határozza meg. A levegőminőség javulását az átszellőzés intenzitásának növelésével is el tudjuk érni. Mérnökként az utóbbira van ráhatásunk az épületek alakjának alkalmas megválasztásával, valamint a növényzet és az egyéb tereptárgyak (pl. parkoló autók) megfelelő elhelyezésével','21','0','user','0','Dr. Papp Bálint
gépészmérnök, kutató (BME Gépészmérnöki Kar, volt E5vös-diák)','23','2024-10-25 09:00:00','2024-10-25 10:00:00','2024-12-28 20:00:00',NULL,NULL,NULL,NULL),
('167','A színházi rendezőasszisztens munkája','Mi a feladata egy rendezőasszisztensnek? Milyen háttérszakmák vannak még a színházban? Mi a különbség a klasszikus kőszínházi struktúra és a független produkciók között? Az előadást azoknak ajánlom, akiket érdekel a kulisszák mögötti világ, a súgók, ügyelők, kellékesek, öltöztetők, díszítők, fodrászok, hangosítók, világosítók birodalma','21','0','user','0','Perényi Luca
rendezőasszisztens (Radnóti Miklós Színház, volt E5vös-diák)','23','2024-10-25 09:00:00','2024-10-25 10:00:00','2024-12-29 20:00:00',NULL,NULL,NULL,NULL),
('168','Az európai intézmények belülről','Az előadó az Eötvös volt diákja, és szívesen vezeti be az Eötvös-diákokat az eurokrata karrierlehetőségekbe. Őszinte kérdések és politikusi válaszok','21','0','user','0','Perger István
a politikai és gazdasági elemzés vezetője (Európai Bizottság Magyarországi Képviselete, volt E5vös-diák)','23','2024-10-25 09:00:00','2024-10-25 10:00:00','2024-12-30 20:00:00',NULL,NULL,NULL,NULL),
('169','Egerek a tudományban','Biológusként végeztem az ELTE-n, és 2005 óta dolgozom az (azóta többször átnevezett) HUN-REN Természettudományi Kutatóközpontban. Laborunkban elsősorban egérkísérleteket végzünk, amelyek segítségével próbáljuk egyre jobban megérteni a meszesedési folyamatokat. A cukorbetegséget és bizonyos genetikai betegségeket is vizsgálunk az egerek segítségével.Előadásomban röviden elmesélném, mikkel foglalkozunk, hogyan telik egy kutató biológus napja, de kicsit általánosabban is beszélnék a kutatómunkáról. Ezért az előadást elsősorban azoknak ajánlom, akik érdeklődnek a természettudományok és a kutatói munka iránt','21','0','user','0','Dr. Pomozi Viola biológus
(HUN-REN Természettudományi Kutatóközpont, volt E5vös-diák)','23','2024-10-25 09:00:00','2024-10-25 10:00:00','2024-12-31 20:00:00',NULL,NULL,NULL,NULL),
('170','Hogy mi a közös a Magnum, a Tanqueray Gin és a kézilabda Európa bajnokság között? Én és a projektmenedzsment','Gondoltad volna, hogy lehet munkaidőben Magnum-ot és Tanqueray Gin-t is kóstolni? Ilyen ez a szakmai ártalom, ha marketingesként dolgozol a legjobb cégek egyikénél.
Ezen kívül a hobbijaidat se kell félretenned, mert a munka mellett ugyanúgy sportolhatsz vagy akár el is mehetsz dolgozni olyan sport világeseményekre, ahol a legnagyobb világsztárok napirendjét egyengetheted. 
Ha érdekel, hogy mi a titkom, gyere el és megtudod, miért érte meg a Közgázon marketingesként végezni és soha fel nem adni azt, ami igazán motivál! 😉','21','0','user','0','Purman Fanni
projektmenedzser (volt E5vös-diák)','23','2024-10-25 09:00:00','2024-10-25 10:00:00','2025-01-01 20:00:00',NULL,NULL,NULL,NULL),
('171','A vállalati pénzügyek világa','Mit csinál egy pénzügyes? Milyen karrierutak és lehetőségek vannak egy pénzügyi diplomával? Mit kell tenni, hogy valaki pénzügyes legyen?','21','0','user','0','Rácz Attila
pénzügyi igazgató (MVM Upstream, volt E5vös-diák)','23','2024-10-25 09:00:00','2024-10-25 10:00:00','2025-01-02 20:00:00',NULL,NULL,NULL,NULL),
('172','Gimis hobbitól az exitig','Gimiben játékprogramokat írtam, és ebből a hobbiból végső soron egy 130 fős cég lett, majd exit. A sikert sokkal nehezebb megérteni, mint a sikertelenséget, de azért megpróbálom, hátha tudok Nektek valami bátorítót és hasznosat mondani','21','0','user','0','Szabó András
’43 éves nyugdíjas’ (volt E5vös-diák)','23','2024-10-25 09:00:00','2024-10-25 10:00:00','2025-01-03 20:00:00',NULL,NULL,NULL,NULL),
('173','Sport, diplomácia, satöbbi','Hogyan keveredik az ember a spanyol király mellé? Mi a teendő, ha megőrül egy zimbabwei? Na és ki akar ott lenni az év legnagyobb hazai sporteseményén?','21','0','user','0','Szántó Dávid, 
sportdiplomata, nemzetközi vezető (Magyar Úszó Szövetség, volt E5vös-diák)','23','2024-10-25 09:00:00','2024-10-25 10:00:00','2025-01-04 20:00:00',NULL,NULL,NULL,NULL),
('174','A budapesti buszközlekedés, mi van mögötte?','Minden érdeklődőnek, aki nyitott a mérnöki tevékenység megismerésére, és persze a közösségi közlekedés – is - érdekli','21','0','user','0','Szedlmajer László
közlekedésmérnök, üzemeltetési igazgató (BKV Zrt.)','23','2024-10-25 09:00:00','2024-10-25 10:00:00','2025-01-05 20:00:00',NULL,NULL,NULL,NULL),
('175','Karrierem története','Miként találtam még a saját utamat az érettségit követően, és milyen kihívások árán?
Az ESSCE nemzetközi egyetemről és a pénzügyi, vállalati menedzsmentről','21','0','user','0','Szepesi András
(Cofidis)','23','2024-10-25 09:00:00','2024-10-25 10:00:00','2025-01-06 20:00:00',NULL,NULL,NULL,NULL),
('176','A technológia és a pszichológia találkozása','Magyarország egyik legnagyobb vállalatának kommunikációs szakértőjeként megtanultam, hogy ez a szakma mennyire színes és mennyi különböző területet ölel fel, amit amikor elindultam ezen az úton, még nem is sejtettem. Amellett, hogy egy multinacionális cégnél dolgozom, pszichológus is vagyok és egy magánpraxist vezetek. A két szakmáról és az idáig vezető útról szívesen mesélek, illetve hogy hogyan is lehet ezeket összeegyeztetetni.
Azoknak ajánlom az előadást, akik érdeklődnek a kommunikáció és a pszichológia iránt, akik kíváncsiak, hogy hogyan lehet akár két hivatást is választani, amik sok szempontból különbözhetnek, de ugyanakkor ki is egészítik egymást','21','0','user','0','Takács Enikő
pszichológus, közgazdász, kommunikációs menedzser
(Samsung Magyarország)','23','2024-10-25 09:00:00','2024-10-25 10:00:00','2025-01-07 20:00:00',NULL,NULL,NULL,NULL),
('177','A világkiállítások bűvöletében - Expo 2020 Dubai, Expo 2025 Osaka','Mi a közös az Eiffel-toronyban, a színes TV-ben és a Viktória-mintás Herendi étkészletben? Mindegyiket az 1851 óta megrendezésre kerülő világkiállítások egyikén mutatták be. Ötévente más-más világváros ad otthont az univerzum egyik legnagyobb show-jának, ahol a hihetetlen találmányok és az úttörő innovációk mellett minden nemzetnek lehetősége nyílik, hogy kulturális sokszínűségét is megmutassa a világnak. Az utolsó, Dubaji Világkiállítás minden korábbinál látványosabbra sikerült, rendkívül színes programok, lenyűgöző látványvilág és monumentális építészeti csodák jellemezték. 2025-ben az Expót Oszakában rendezik, a szervezők a 184 nap alatt több mint 28 millió látogatót várnak. 
Milyen lesz a Magyar Pavilon Oszakában? Mit mutatunk meg a magyar kultúrából és gasztronómiából? Kik és mik a “magyar hírességek” Japánban? Első kézből kaptok választ ezekre a kérdésekre is az Expo Magyar Pavilonjának szakmai és üzleti programjaiért felelős igazgatójától','21','0','user','0','Török Barbara
az Expo Magyar Pavilonjának szakmai és üzleti programjaiért felelős igazgatója (volt E5vös-diák)','23','2024-10-25 09:00:00','2024-10-25 10:00:00','2025-01-08 20:00:00',NULL,NULL,NULL,NULL),
('178','Motion design - grafika mozgásban','Bemutató az animáció / mozgó grafika készítéséről és szerepéről különböző felületeken - TV csatornák és műsorok arculatában, színpadi látványelemként, videoklipekben. Néhány példán keresztül megismerhetjük, hogy hogyan lesz mozgókép egy grafikai ötletből, milyen egyéni tudás és képesség hasznos ebben a szakmában, és hogyan kapcsolódik egymáshoz a grafikai tervezés és a technológia.
Mindenkinek ajánlott, akit érdekel a vizualitás és a mozgókép, és kíváncsi arra, hogy mit csinál az, akinek ez a munkája','21','0','user','0','Varsányi Pál
grafikus, animátor, arculattervező (volt E5vös-diák)','23','2024-10-25 09:00:00','2024-10-25 10:00:00','2025-01-09 20:00:00',NULL,NULL,NULL,NULL),
('179','Könyvet a borítójáról... – hogyan születnek a könyvborítók?','Fontos az első benyomás, és ez a könyvek világában sincs másképp. A jó könyvborító igazodik a szöveg műfajához, tartalmához és emlékezetes is. De milyen eszköztárral lehet formálni egy borítót, miért fontos a tipográfia, és mekkora a szabadsága a tervezőnek? Ismerd meg a könyvborító tervezés útját és egy tervezőgrafikus mindennapjait!
Ha érdekel a tervezőgrafika, az illusztráció vagy az irodalom, akkor gyere, és hozd magaddal azt a könyvet is, aminek a legjobban szereted a borítóját!','21','0','user','0','Visnyai Zoltán
tervezőgrafikus (Magvető Kiadó, volt E5vös-diák)','23','2024-10-25 09:00:00','2024-10-25 10:00:00','2025-01-10 20:00:00',NULL,NULL,NULL,NULL),
('180','Út az orvosi pályához - utak az orvosi pályán ','Érdekel az orvosi pálya? Honnan tudhatod, hogy neked való? Mire készülj? Milyen lehetőségeket rejt? (Leginkább a 11. és 12. évfolyam diákjainak ajánlott)','22','0','user','0','Dr. Berta Gabriella orvos - Dr. Kolosy Béla orvos, orvosszakmai tréningmenedzser (Egis Gyógyszergyár Zrt.)','30','2024-10-25 10:15:00','2024-10-25 11:00:00','2025-01-11 20:00:00',NULL,NULL,NULL,209),
('181','A magyar igazságszolgáltatás ','Életünk során szinte minden nap találkozunk az igazságszolgáltatással valamilyen formában, mégis, többen csak akkor ismerik meg annak működését, ha közvetlen dolguk akad vele. Prezentációmmal én ezen szeretnék változtatni. Az előadás meghallgatásához semmilyen alaptudás nem szükséges, ugyanis csupán egy laikus érdeklődő lelkes "beavatója" lesz a témába. Mert, ahogy egy kedves barátom mondta nekem: All you need is Law!','22','0','user','0','Boros Marcel (12. F)','30','2024-10-25 10:15:00','2024-10-25 11:00:00','2025-01-12 20:00:00',NULL,NULL,NULL,210),
('182','Véradás és transzplantáció ','Egy véradással 3 emberi életet menthetsz meg. De hogy jön ki ez a szám? Mik a feltételei annak, hogy véradó lehess? Egyáltalán miért olyan nélkülözhetetlen a vér a szervezetünk számára? És hogy is voltak azok a fránya vércsoportok? A szervtranszplantáció életet ment. De miért lesz valakinek szüksége új szervre? És hogyan lesz valakiből donor? Milyen jogaid vannak ezzel kapcsolatban? Mit is jelent az, ha valaki agyhalott?
Ha ezek az izgalmas kérdések felkeltették az érdeklődésedet, akkor az előadásunkon a helyed! (Az előadások a 9. évfolyamtól ajánlottak)','22','0','user','0','Budapesti Orvostanhallgatók Egyesülete - Véradás és Transzplantáció szekció','30','2024-10-25 10:15:00','2024-10-25 11:00:00','2025-01-13 20:00:00',NULL,NULL,NULL,212),
('183','Logikai játékok, ördöglakatok, térbeli kirakók ','Kisebb illetve nagyobb kihívást jelentő játékok. Akkor gyere, ha szeretsz gondolkodni, alkotni, és van benned kitartás - mert lesznek olyan fejtörők, amiket nem tudsz gyorsan megfejteni!','22','0','user','0','Deák Anna tanárnő (volt E5vös-diák)','15','2024-10-25 10:15:00','2024-10-25 11:00:00','2025-01-14 20:00:00',NULL,NULL,NULL,213),
('184','Újdonságok a fizikában - érthetően','Az előadás a gravitációnak egy új, izgalmas értelmezését mutatja be, képletek nélkül, nemcsak a fizika tagozatosok számára érthetően. Áttekinti a fizika története során felmerült különféle elképzeléseket Newtontól Einsteinig - és ha az idő engedi, még azt is megbeszéljük, hogy mi is az a Higgs-bozon (Leginkább 10. évfolyamtól ajánlott!)','22','0','user','0','Farkas Péter mérnök, projektvezető','30','2024-10-25 10:15:00','2024-10-25 11:00:00','2025-01-15 20:00:00',NULL,NULL,NULL,NULL),
('185','Játszunk kirakóst! (tangram)','A tangram egy 7 elemből álló kínai kirakó játék. Rengeteg ismert feladvány van, de lehet sajátot is gyártani - Előadás + játék + közös munka is lesz','22','0','user','0','Feke Zsolt tanár úr','30','2024-10-25 10:15:00','2024-10-25 11:00:00','2025-01-16 20:00:00',NULL,NULL,NULL,NULL),
('186','Ínyenceknek. Rómaiak-e a románok? Egy nép eredete a történelemhamisításban és a tények tükrében ','Ínyenceknek. Rómaiak-e a románok? Egy nép eredete a történelemhamisításban és a tények tükrében','22','0','user','0','Forró István nyugdíjas vezetőtanár','30','2024-10-25 10:15:00','2024-10-25 11:00:00','2025-01-17 20:00:00',NULL,NULL,NULL,215),
('187','Oroszok a Baltikumban a livóniai háborútól napjainkig ','Középkori Hanza-városok a Baltikumban - harmóniában a modern építészettel. Várostervezés, ételek, skandináv életmód-trendek, természeti környezet, a finnugor észt nyelv bemutatása, gazdaságföldrajz. A livóniai háborúban a moszkvai uralkodó, Rettegett Iván elpusztította a virágzó Hanza-városokat, idegen lakosokat telepített be. A 17. és 18. században óhitűek menekültek a Baltikumba, akik nem fogadták el Nyikon pátriárka reformjait. A 19. században Jūrmala lettországi tengeri üdülőhely az orosz intelligencia inspiráló helye volt. A szovjet időkben lumpenproletár elemek politikailag támogatott bevándorlásával alulképzett és alulkulturált réteg áramlott mindhárom balti köztársaságba az erős hagyományú, saját kultúrát őrző helyi nemzetek rombolására. A 20. és a 21. század fordulójának szociológiai kutatásai szerint az új generációs helyi oroszok identitása már baltikumi. Fiataljaik az észtországi svéd és angol nyelvű középiskolákba igyekeznek. A túlnyomórészt orosz lakosú Narva észt város körzetében 10 éve készült felmérés szerint a helyi oroszok nem kívánnak semmilyen keleti beavatkozást. (Az előadás alatt feladatokra is válaszolni kell saját okoseszköz használatával! Aktív diákok jöjjenek! 11. évfolyamtól ajánlott!)','22','0','user','0','Dr. Földvári Sándor Baltikum-kutató, volt egyetemi oktató (volt E5vös-diák)','30','2024-10-25 10:15:00','2024-10-25 11:00:00','2025-01-18 20:00:00',NULL,NULL,NULL,216),
('188','Látványos kémiai kísérletek','Szeretnéd látni hogy mivel mosnak fogat az elefántok? Vajon létezik éghetetlen zsebkendő? Láttál már kígyót tojásból kikelni? És működő tűzhányókat? Tudtad hogy van olyan óra, ami nem tiktakol, és időre változtatja a színét? Ha bármelyikre kíváncsi vagy, akkor itt a helyed!','22','0','user','0','Hajdú Dorottya egyetemi hallgató (BME biotechnológia, volt E5vös-diák) - Fodor Izabella egyetemi hallgató (BME biomérnök) - Szirmai Ádám PhD-hallgató (ELTE kémia, volt E5vös-diák), Várady Zalán PhD-hallgató (BME vegyészmérnök)','30','2024-10-25 10:15:00','2024-10-25 11:00:00','2025-01-19 20:00:00',NULL,NULL,NULL,NULL),
('189','Repülni akarok! - Tények és mítoszok a légiutaskísérő hivatásról','Miért "álom munka" a repülés? Tényleg az? Kinek való? Érdemes ma légiutaskísérőnek jelentkezni? Segíti a későbbi karrieremet, vagy nehezíti? Hány nyelvet kell beszélni? Igaz, hogy a jelentkezéshez kell tudni ejtőernyőzni? Miből kell felvételizni? Rövid előadás és utána kérdezz-felelek arról, hogy hogyan lehet valakiből légiutaskísérő','22','0','user','0','Hartyáni Emőke volt légiutaskísérő, légiközlekedési szakember','30','2024-10-25 10:15:00','2024-10-25 11:00:00','2025-01-20 20:00:00',NULL,NULL,NULL,NULL),
('190','A közösségi média és Te','A közösségi médiumok a mai diákoknak már nem tanulandó, hanem ösztönösen használható kommunikációs csatornák. Ennek ellenére vannak olyan általános aranyszabályok, melyeket érdemes megismerni ahhoz, hogy hasznosan és örömmel használhassuk mind a jelenlegi, mind pedig a még nem létező, jövőbeli közösségi média platformokat. Egy előadás a világ 70 certified social media strategist-ek egyikétől','22','0','user','0','Herczeg Attila közösségi média tanácsadó (volt E5vös-diák)','30','2024-10-25 10:15:00','2024-10-25 11:00:00','2025-01-21 20:00:00',NULL,NULL,NULL,NULL),
('191','Kiterjesztett valóság és annak használata','A kiterjesztett valóság olyan technológia, amely a valódi világot virtuális elemekkel egészíti ki, ezzel újfajta élményeket teremtve. Képzelj el egy világot, ahol a telefonod vagy egy speciális szemüveg segítségével a környezetedbe vetített 3D-s objektumokkal léphetsz kapcsolatba. Ezzel nemcsak a szórakozási lehetőségeink bővülnek, hanem az oktatás, a munka, sőt, akár a műtétek során is rendkívül hasznos lehet! Az előadás során egy ilyen szemüveg is bemutatásra kerül','22','0','user','0','Dr. Hideg Attila informatikus, adjunktus (BME Villamosmérnöki és Informatikai Kar, volt E5vös-diák)','30','2024-10-25 10:15:00','2024-10-25 11:00:00','2025-01-22 20:00:00',NULL,NULL,NULL,NULL),
('192','Beszédtechnikai gyakorlatok','Érdekel miben tér el egy színész beszéde a köznapi beszédtől? Kíváncsi vagy, hogyan zajlik a színészhallgatók beszédtechnikai oktatása? Szeretnél te is elsajátítani pár trükköt, hogy
érthetőbb legyen a beszéded? Gyere és próbálj ki gyakorlatokat a Színház- és Filmművészeti Egyetem egyik beszédtanárával, egy volt E5vös-diákkal!','22','0','user','0','Király Katalin beszédtechnika tanár (Színház- és Filmművészeti Egy., volt E5vös-diák)','15','2024-10-25 10:15:00','2024-10-25 11:00:00','2025-01-23 20:00:00',NULL,NULL,NULL,NULL),
('193','A matematikai hatszögszámok ','Látványos algebrai és geometriai bizonyításokkal mindenkinek érthető módon. (A matematikás osztályokba és matematika fakultációra járó diákoknak különösen ajánlott)','22','0','user','0','Dr. Molnár István matematikus, egyetemi docens (Gál Ferenc Egy. Gazdasági Kar)','30','2024-10-25 10:15:00','2024-10-25 11:00:00','2025-01-24 20:00:00',NULL,NULL,NULL,218),
('194','Én mégis mit tehetek?! (személyes kapcsolódás a környezetvédelemmel) ','"Én mégis mit tehetek a környezetért?!" Gyere, és megmutatom! Mert szinte mindenben, a leghétköznapibb választásodban is ott a lehetőség, hogy a környezeti szempontokat figyelembe véve éld az életed. Egy piknik maradékait fogjuk elemezni, hogy közben egy kicsit a saját szokásainkon is elgondolkodjunk. Figyelem! A programban való részvételhez a világmegváltási szándék nem elvárás. De előnyt jelent','22','0','user','0','Névery Dorottya környezeti nevelő (Magyar Madártani és Természetvédelmi Egyesület)','30','2024-10-25 10:15:00','2024-10-25 11:00:00','2025-01-25 20:00:00',NULL,NULL,NULL,219),
('195','Egy színházi előadás létrehozása: a megálmodástól - sok nehézségen át - a megvalósításig','Bizonyára sokan gondolkodtatok már rajta, milyen fantasztikus lenne egy saját színházi előadást létrehozni és bemutatni a nagyérdeműnek... Nos, nekem ez a múlt évad végén sikerült! Előadásomban mesélek tapasztalataimról az ötletelés fázisától, a szerzői jogok kezelésén, rendezésen és színpadtechnikán át, az éles bemutatóig mindenről. És természetesen szívesen válaszolok a kérdéseitekre is!','22','0','user','0','Schreck Péter (12. F)','30','2024-10-25 10:15:00','2024-10-25 11:00:00','2025-01-26 20:00:00',NULL,NULL,NULL,NULL),
('196','A tudomány valóban eltemette Istent?','A technológia és tudomány fejlettségének korszakában intellektuálisan igazán tarthatatlan álláspont a teizmus? Minden kérdést megválaszolhatnak a természettudományok a világunkkal kapcsolatban? Az istenhit csak hátráltatja a tudományt? Lássuk mit gondol ezekről a kérdésekről egy eötvös-diák (egy csöpp keresztény elfogultsággal 😉)! 30 perc előadás, utána beszélgetés','22','0','user','0','Simon András Márk (12. B)','30','2024-10-25 10:15:00','2024-10-25 11:00:00','2025-01-27 20:00:00',NULL,NULL,NULL,NULL),
('197','A globális energiakihívás közgazdaságtana','Nem lévén energetikus, de képzett kvantitatív közgazdász vagyok, a globális energiakihívást legegyszerűbben egy elismert amerikai szakember, Michael Greenstone, a Chicagói Egyetem tanárának 2024-es előadásán keresztül mutatom be, ami példát mutat az ökológiai problémák főáramú gazdaságtani tárgyalására. A globális energiakihívást nem elszigetelten, hanem az összes ország összefogásával kell kezelni, figyelembevéve az átváltást három összefüggő, de ellentétes cél között: legyen olcsó és megbízható energia, legyen tiszta levegő és korlátozzuk a globális felmelegedés kárait. Tényeket mutatunk be, amelyek segítenek a kihívás megvilágításában és a célok megértésében. Majd lehetséges megoldásokat vázolunk, amelyek figyelembe veszik az energia teljes társadalmi költségét, a műszaki fejlesztésen túl a gazdasági mechanizmusokat is megújítja, emellett pontosítja a környezetszennyezés és a felmelegedés okozta károkról szóló információkat','22','0','user','0','Dr. Simonovits András nyugdíjas matematikus, közgazdász, professzor (BME Matematikai Int.)','30','2024-10-25 10:15:00','2024-10-25 11:00:00','2025-01-28 20:00:00',NULL,NULL,NULL,NULL),
('198','Minden, amit a külföldi továbbtanulásról tudni kell ','Szeretnél bejutni álmaid egyetemére Dániában, Svédországban, Belgiumban, Hollandiában, Németországban, Svájcban, Olaszországban vagy esetleg a szomszédunkban, Ausztriában? Miként válassz intézményt vagy szakot? Hogyan készülj fel a tanulmányaidra szakmailag és nyelvileg? Hogy kerüld el a buktatókat? Ezekre és még sok más kérdésre keressük a választ a több évtizedes tapasztalattal rendelkező oktatási tanácsadó közreműködésével','22','0','user','0','Dr. Soós János alapító (Studium Akadémia)','30','2024-10-25 10:15:00','2024-10-25 11:00:00','2025-01-29 20:00:00',NULL,NULL,NULL,222),
('199','…de egyes szavazatok valóban egyenlőbbek a többinél? - További érdekességek a választási rendszerek világából ','Hogyan lesznek szavazatokból mandátumok? Mit jelent az, hogy nyílt vagy zárt egy választási lista? A több győzteses választási rendszerek alapjai, a “többségi” és arányos formulák, no és a gerrymandering. (Az előadás előzetes ismereteket nem igényel, az előző előadáson való részvételt sem. De interaktív, ezért a mobiltelefon használata ajánlott!)','22','0','user','0','Stankovics Ábel egyetemi hallgató (ELTE ÁJK, volt E5vös-diák)','30','2024-10-25 10:15:00','2024-10-25 11:00:00','2025-01-30 20:00:00',NULL,NULL,NULL,223),
('200','Aranyon nem fog a rozsda - Az emberiség és az arany közös történetének első fejezete','Az arany az emberiség történelmét leginkább formáló fém. Háború, felfedezés, béke, művészet, vándorlás: megannyi példát lehetne sorolni az elmúlt több ezer évből, melyben az arany központi szerepet töltött és tölt be. A jelen idő használata is teljesen jogos, hiszen az arany megkerülhetetlen tényezője napjainknak is. Ráadásul nem csak mint nyersanyag van jelen életünkben: közmondások, költői képek, mesék és metaforák tömkelege jelzi, hogy az arany, mint szimbólum is összefonódott az emberiséggel. Arról azonban kevés szó esik, hogy hogyan találkozott először az ember az arannyal, mikor, hol és hogyan jelentek meg az első aranytárgyak, és mi lehetett az akkori emberek célja e fémmel. Az előadásban az arany és az ember közös történetének első fejezetéről lesz szó, az első aranytárgyakról, az aranyművesség kezdeteiről és az arany szimbolikájának kialakulásáról','22','0','user','0','Dr. Szilágyi Márton régész (ELTE BTK, volt E5vös-diák)','30','2024-10-25 10:15:00','2024-10-25 11:00:00','2025-01-31 20:00:00',NULL,NULL,NULL,NULL),
('201','Mit csinál az adattudós? Miért izgalmas adatokkal foglalkozni?','Az ELTE Informatikai Karán az Adattudományi Tanszéken nem hagyományos kutatásokat végzünk, jellemzően vállalkozásoknak segítünk az adataik hasznosításában. Az, hogy az adatok miért olyan fontosak ma már talán nem kérdés, de ettől még megfoghatatlannak tűnik sokaknak. Ennek a világnak az alapjaiba vezetném a hallgatóságot, néhány valódi példával','22','0','user','0','Tarcsi Ádám adattudós (ELTE Informatikai Kar)','30','2024-10-25 10:15:00','2024-10-25 11:00:00','2025-02-01 20:00:00',NULL,NULL,NULL,NULL),
('202','Üzenet a palackban - Lehet a szemétszedés közösségi élmény? Hulladékból innováció?','“Lépj a fedélzetre!”, nézz jól körül, majd helyezkedj el kényelmesen és hallgasd meg a petkalózok élménybeszámolóját! Történeteik elrepítenek a Tisza varázslatos ártéri erdeibe, vagy egy lakatlan szigetre Jánd közelében. Mesélnek arról, hogy expedíciójuk során miként jártak be 6 országot azért, hogy felhívják a figyelmet a folyami hulladékszennyezésre. Bepillantást nyerhetsz a PET Kupa izgalmas, rendkívül szerteágazó tevékenységébe, sőt akár be is kapcsolódhatsz! De vigyázz! Aki belekóstol, örökre rabja lesz. Sokak szerint függőséget okoz, mert az elszántság kreativitással párosul, ami rendkívül inspiráló. Naponta születnek új ötletek csapaton belül is, és állnak az ügy mellé szakemberek, cégek, művészek, akik innovatív megoldásokkal segítik a munkát. Az együttműködések pedig fantasztikus eredményeket hoznak! Legfontosabb eredmény azonban a folyók ügye mentén kialakult, egyre bővülő közösség. Velünk tartasz?','22','0','user','0','Vészity Katalin szemléletformálási csoportvezető (PET Kupa Egyesület)','30','2024-10-25 10:15:00','2024-10-25 11:00:00','2025-02-02 20:00:00',NULL,NULL,NULL,NULL),
('203','Programozzunk együtt egy scratch platformert! ','Leginkább olyanok jöjjenek, akiket érdekel ez a téma és tudnak már valamennyire programozni!','22','0','user','0','Xu Jianan (9. A)','15','2024-10-25 10:15:00','2024-10-25 11:00:00','2025-02-03 20:00:00',NULL,NULL,NULL,230),
('204','A kínai és a magyar kultúra összehasonlítása','Milyen hasonlóságok és különbségek vannak a magyar és a kínai nyelv és kultúra között? Mindezt az előadásunkból megtudhatod, ahogy azt is, milyen szuper lehetőséggel juthatsz ki Kínába, akár már idén is','22','0','user','0','A YOLO Education munkatársai: Niu Zhinan kínai nyelvtanár, igazgató - Szádovszkyné Lőrincz Kata kínai nyelvtanár, igazgatói asszisztens - az iskola kínai nyelvtanárai','30','2024-10-25 10:15:00','2024-10-25 11:00:00','2025-02-04 20:00:00',NULL,NULL,NULL,NULL),
('205','A fenntarthatóság és a talajvédelem fontossága a mezőgazdasági gyakorlatban.','Humán egészségügyi vonatkozásokkal','22','0','user','0','Dr. Gergácz Zoltán (Kányai Mezőgazdasági Zrt. Igazgatóság elnöke)','30','2024-10-25 10:15:00','2024-10-25 11:00:00','2025-02-05 20:00:00',NULL,NULL,NULL,NULL),
('206','✨Határvédelem but it"s very demure✨','Nem kell szorongani, ha meg akarod húzni a határaidat. Legyél a saját életed főszereplője, anélkül, hogy a FOMO csapdájába kerülnél!','23','0','user','0','Bakai Lili egyetemi hallgató, aktivista (NANE Egyesület)','20','2024-10-25 11:15:00','2024-10-25 12:00:00','2025-02-06 20:00:00',NULL,NULL,NULL,NULL),
('207','Hol (nem) találsz lézert? - avagy a trigonometriától a Nobel-díjig','A lézerek a mai napig ámulatot keltenek annak ellenére, hogy szinte nincs olyan terület, ahol ne alkalmaznák. Az előadás - a teljesség igénye nélkül - felvillant néhányat mind a köznapi, mind az extrém alkalmazásokból. Ehhez kapcsolódóan igyekszik a fizikai hátteret is megvilágítani, amihez - kezdetnek - elegendő egy kis trigonometria. Még arra is fény derülhet, hogyan lesz a kezdetből Nobel-díj. Végül helyszíni bemutatóval az előadóteremben is világítunk. (A sin(x) és cos(x) függvények ismerete szükséges az előadás megértéséhez!)','23','0','user','0','Dr. Barócsi Attila villamosmérnök, egyetemi docens (BME Természettudományi Kar)','30','2024-10-25 11:15:00','2024-10-25 12:00:00','2025-02-07 20:00:00',NULL,NULL,NULL,NULL),
('208','Gyógy- és mérgező növények a házunk táján','A növények mindennapi életünk részei. Körülvesznek minket a kertben, gyomnövényként vagy éppen dísznövényként a szobában. Lehetnek ehetők, gyógyító hatásúak vagy akár mérgezők is. A "paracelsusi törvény" alapján minden anyag – így a növény is – nagy dózisban lehet méreg, kis dózisban pedig orvosság. Konkrét példákon keresztül kerül bemutatásra mi a különbség a mérgező és az erős hatású fajok között. Mely fajoktól óvakodjunk, melyeket használhatjuk nyugodtan gyógyításra?','23','0','user','0','Professzor Dr. Bernáth Jenő gyógynövénykutató, egyetemi tanár (Magyar Agrár- és Élettud. Egy. Kertészettud. Int. )','30','2024-10-25 11:15:00','2024-10-25 12:00:00','2025-02-08 20:00:00',NULL,NULL,NULL,NULL),
('209','Út az orvosi pályához - utak az orvosi pályán ','Érdekel az orvosi pálya? Honnan tudhatod, hogy neked való? Mire készülj? Milyen lehetőségeket rejt? (Leginkább a 11. és 12. évfolyam diákjainak ajánlott)','23','0','user','0','Dr. Berta Gabriella orvos - Dr. Kolosy Béla orvos, orvosszakmai tréningmenedzser (Egis Gyógyszergyár Zrt.)','30','2024-10-25 11:15:00','2024-10-25 12:00:00','2025-02-09 20:00:00',NULL,NULL,180,NULL),
('210','A magyar igazságszolgáltatás ','Életünk során szinte minden nap találkozunk az igazságszolgáltatással valamilyen formában, mégis, többen csak akkor ismerik meg annak működését, ha közvetlen dolguk akad vele. Prezentációmmal én ezen szeretnék változtatni. Az előadás meghallgatásához semmilyen alaptudás nem szükséges, ugyanis csupán egy laikus érdeklődő lelkes "beavatója" lesz a témába. Mert, ahogy egy kedves barátom mondta nekem: All you need is Law!','23','0','user','0','Boros Marcel (12. F)','30','2024-10-25 11:15:00','2024-10-25 12:00:00','2025-02-10 20:00:00',NULL,NULL,181,NULL),
('211','Rendhagyó énekóra','A rendhagyó énekóra folyamán arra törekszem, hogy a zenetörténetet egy kicsit közelebb hozzam a diákok számára, és megszerettessem velük a zeneszerzők emberközeli bemutatásával. A tanóra tematikája egyfajta fantázia olyan érdekességekkel, amelyek lehetőség szerint minden korból valók. A történeti elemeken túl a műfajokkal is igyekszem megismertetni a tanulókat, akik természetesen kérdezhetnek, illetve az általam feltett kérdésekre válaszokat is várok tőlük','23','0','user','0','Bősze Ádám zenetörténész','30','2024-10-25 11:15:00','2024-10-25 12:00:00','2025-02-11 20:00:00',NULL,NULL,NULL,NULL),
('212','Véradás és transzplantáció ','Egy véradással 3 emberi életet menthetsz meg. De hogy jön ki ez a szám? Mik a feltételei annak, hogy véradó lehess? Egyáltalán miért olyan nélkülözhetetlen a vér a szervezetünk számára? És hogy is voltak azok a fránya vércsoportok? A szervtranszplantáció életet ment. De miért lesz valakinek szüksége új szervre? És hogyan lesz valakiből donor? Milyen jogaid vannak ezzel kapcsolatban? Mit is jelent az, ha valaki agyhalott?
Ha ezek az izgalmas kérdések felkeltették az érdeklődésedet, akkor az előadásunkon a helyed! (Az előadások a 9. évfolyamtól ajánlottak)','23','0','user','0','Budapesti Orvostanhallgatók Egyesülete - Véradás és Transzplantáció szekció','30','2024-10-25 11:15:00','2024-10-25 12:00:00','2025-02-12 20:00:00',NULL,NULL,182,NULL),
('213','Logikai játékok, ördöglakatok, térbeli kirakók ','Kisebb illetve nagyobb kihívást jelentő játékok. Akkor gyere, ha szeretsz gondolkodni, alkotni, és van benned kitartás - mert lesznek olyan fejtörők, amiket nem tudsz gyorsan megfejteni!','23','0','user','0','Deák Anna tanárnő (volt E5vös-diák)','15','2024-10-25 11:15:00','2024-10-25 12:00:00','2025-02-13 20:00:00',NULL,NULL,183,NULL),
('214','Sorstragédiák a magyar labdarúgás történetében','Mi lett volna, ha ...!? Szerencsétlenség vagy felkészületlenség vezetett odáig, hogy már Málta és Andorra is legyőzte a magyar válogatottat? Hogyan jutottunk el a vb-döntőktől a vb-selejtezők számolgatásáig...','23','0','user','0','Farkas Csongor tanár úr','30','2024-10-25 11:15:00','2024-10-25 12:00:00','2025-02-14 20:00:00',NULL,NULL,NULL,NULL),
('215','Ínyenceknek. Rómaiak-e a románok? Egy nép eredete a történelemhamisításban és a tények tükrében ','Ínyenceknek. Rómaiak-e a románok? Egy nép eredete a történelemhamisításban és a tények tükrében','23','0','user','0','Forró István nyugdíjas vezetőtanár','30','2024-10-25 11:15:00','2024-10-25 12:00:00','2025-02-15 20:00:00',NULL,NULL,186,NULL),
('216','Oroszok a Baltikumban a livóniai háborútól napjainkig ','Középkori Hanza-városok a Baltikumban - harmóniában a modern építészettel. Várostervezés, ételek, skandináv életmód-trendek, természeti környezet, a finnugor észt nyelv bemutatása, gazdaságföldrajz. A livóniai háborúban a moszkvai uralkodó, Rettegett Iván elpusztította a virágzó Hanza-városokat, idegen lakosokat telepített be. A 17. és 18. században óhitűek menekültek a Baltikumba, akik nem fogadták el Nyikon pátriárka reformjait. A 19. században Jūrmala lettországi tengeri üdülőhely az orosz intelligencia inspiráló helye volt. A szovjet időkben lumpenproletár elemek politikailag támogatott bevándorlásával alulképzett és alulkulturált réteg áramlott mindhárom balti köztársaságba az erős hagyományú, saját kultúrát őrző helyi nemzetek rombolására. A 20. és a 21. század fordulójának szociológiai kutatásai szerint az új generációs helyi oroszok identitása már baltikumi. Fiataljaik az észtországi svéd és angol nyelvű középiskolákba igyekeznek. A túlnyomórészt orosz lakosú Narva észt város körzetében 10 éve készült felmérés szerint a helyi oroszok nem kívánnak semmilyen keleti beavatkozást. (Az előadás alatt feladatokra is válaszolni kell saját okoseszköz használatával! Aktív diákok jöjjenek! 11. évfolyamtól ajánlott!)','23','0','user','0','Dr. Földvári Sándor Baltikum-kutató, volt egyetemi oktató (volt E5vös-diák)','30','2024-10-25 11:15:00','2024-10-25 12:00:00','2025-02-16 20:00:00',NULL,NULL,187,NULL),
('217','Harry Potter tényleg tudott latinul?!','Egy holt nyelv hogyan élhet tovább napjainkban? Mi köze a latinnak a roxforti varázsvilághoz? Mitológiai motívumok, beszélő nevek, beszédes varázsigék a népszerű regénysorozatban - a 10-dikes latinosok interaktív előadásában (Okoseszköz használandó!)','23','0','user','0','Haluska Olívia (10. F) - Kislinder Viola - Solymosi-Kabdebó Emma (mindketten: 10. D)','30','2024-10-25 11:15:00','2024-10-25 12:00:00','2025-02-17 20:00:00',NULL,NULL,NULL,NULL),
('218','A matematikai hatszögszámok ','Látványos algebrai és geometriai bizonyításokkal mindenkinek érthető módon. (A matematikás osztályokba és matematika fakultációra járó diákoknak különösen ajánlott)','23','0','user','0','Dr. Molnár István matematikus, egyetemi docens (Gál Ferenc Egy. Gazdasági Kar)','30','2024-10-25 11:15:00','2024-10-25 12:00:00','2025-02-18 20:00:00',NULL,NULL,193,NULL),
('219','Én mégis mit tehetek?! (személyes kapcsolódás a környezetvédelemmel) ','"Én mégis mit tehetek a környezetért?!" Gyere, és megmutatom! Mert szinte mindenben, a leghétköznapibb választásodban is ott a lehetőség, hogy a környezeti szempontokat figyelembe véve éld az életed. Egy piknik maradékait fogjuk elemezni, hogy közben egy kicsit a saját szokásainkon is elgondolkodjunk. Figyelem! A programban való részvételhez a világmegváltási szándék nem elvárás. De előnyt jelent','23','0','user','0','Névery Dorottya környezeti nevelő (Magyar Madártani és Természetvédelmi Egyesület)','30','2024-10-25 11:15:00','2024-10-25 12:00:00','2025-02-19 20:00:00',NULL,NULL,194,NULL),
('220','Mit csinál a szimulációs mérnök?','Mit csinál a szimulációs mérnök? Szimulál! Olyan dolgokat számol ki, amelyek megépítésére nem lenne erőforrás (pénz, anyag, idő), ezért csak azt kell megépíteni, ami működik. Milyen módszerrel dolgozunk és milyen képességek szükségesek egy ilyen álláshoz?','23','0','user','0','Reichardt András villamosmérnök, mesteroktató (BME Villamosmérnöki és Informatikai Kar)','30','2024-10-25 11:15:00','2024-10-25 12:00:00','2025-02-20 20:00:00',NULL,NULL,NULL,NULL),
('221','Egy Eötvös-diák éve Amerikában','Érdekel, milyen lehet cserediáknak lenni az USA-ban? Te is szeretnél egy évig külföldön tanulni? Az előadásomon beszámolót tartok az amerikai évemről ASSIST ösztöndíjasként, elmesélem a tapasztalataimat a külföldi tanulásról, és megválaszolom az összes kérdéseteket az amerikai élettel és az ASSIST ösztöndíjjal kapcsolatban (Az előadás a 8-11. évfolyamosoknak ajánlott, mert ők tudnak jelentkezni az ösztöndíjra)','23','0','user','0','Sipos Petra (11. B)','30','2024-10-25 11:15:00','2024-10-25 12:00:00','2025-02-21 20:00:00',NULL,NULL,NULL,NULL),
('222','Minden, amit a külföldi továbbtanulásról tudni kell ','Szeretnél bejutni álmaid egyetemére Dániában, Svédországban, Belgiumban, Hollandiában, Németországban, Svájcban, Olaszországban vagy esetleg a szomszédunkban, Ausztriában? Miként válassz intézményt vagy szakot? Hogyan készülj fel a tanulmányaidra szakmailag és nyelvileg? Hogy kerüld el a buktatókat? Ezekre és még sok más kérdésre keressük a választ a több évtizedes tapasztalattal rendelkező oktatási tanácsadó közreműködésével','23','0','user','0','Dr. Soós János alapító (Studium Akadémia)','30','2024-10-25 11:15:00','2024-10-25 12:00:00','2025-02-22 20:00:00',NULL,NULL,198,NULL),
('223','…de egyes szavazatok valóban egyenlőbbek a többinél? - További érdekességek a választási rendszerek világából ','Hogyan lesznek szavazatokból mandátumok? Mit jelent az, hogy nyílt vagy zárt egy választási lista? A több győzteses választási rendszerek alapjai, a “többségi” és arányos formulák, no és a gerrymandering. (Az előadás előzetes ismereteket nem igényel, az előző előadáson való részvételt sem. De interaktív, ezért a mobiltelefon használata ajánlott!)','23','0','user','0','Stankovics Ábel egyetemi hallgató (ELTE ÁJK, volt E5vös-diák)','30','2024-10-25 11:15:00','2024-10-25 12:00:00','2025-02-23 20:00:00',NULL,NULL,199,NULL),
('224','EJG-ből a BME VIK-re, mire készüljek? - gólya-szemszög','Az első napok, az első hetek, az első hónapok az ország egyik legjobb egyetemén. Mit tanul egy mérnökinformatikus hallgató? Nehéz feladat ez? Kell tudni programozni? Milyen hely a BME? Jó a közösség? Milyenek a "tanárok"? Mi történt a gólyatáborban, hol az igazság? Milyen fakultációt válasszak? Miből érettségizzek? Számít ez egyáltalán? A "középiskola - egyetem"-átmenet? Felkészülés a nyár végén? Az egyetemi Neptun-rendszer tényleg nagyon problémás? De mi is az a Neptun-rendszer? Hogyan maradjak informált? Hogyan láthatok bele az egyetemi életbe már most? Lásd a BME VIK-et olyan szemszögből, ahogy még soha!','23','0','user','0','Szőcs Barnabás "Zolika" egyetemi hallgató (BME Villamosmérnöki Kar, 13. D)','30','2024-10-25 11:15:00','2024-10-25 12:00:00','2025-02-24 20:00:00',NULL,NULL,NULL,NULL),
('225','Frankenstein and friends (Frankenstein és barátai) - az előadás nyelve angol!','Understanding the undead - grave lessons in creativity. A talk about how Frankenstein, Dracula and Zombies help us know what it is to be human','23','0','user','0','Tacey Richard "szörny-rajongó"','30','2024-10-25 11:15:00','2024-10-25 12:00:00','2025-02-25 20:00:00',NULL,NULL,NULL,NULL),
('226','Nők a munkapiacon - döntések, kényszerek, diszkrimináció','Miért keresnek kevesebbet a nők, mint a férfiak? Miért a nők maradnak otthon a gyerekekkel? Diszkriminálják a nőket, vagy saját döntésből választanak kevésbé jól fizető állásokat? Az előadás ezeket a kérdéseket járja körül, és a közgazdaságtan módszereivel keresi a lehetséges magyarázatokat (Az előadás a 9. évfolyamtól ajánlott)','23','0','user','0','Dr. Telegdy Álmos közgazdász, egyetemi docens (BCE)','30','2024-10-25 11:15:00','2024-10-25 12:00:00','2025-02-26 20:00:00',NULL,NULL,NULL,NULL),
('227','70 éves a CERN! - születésnapi áttekintés','A CERN 70 éves történetének legérdekesebb és legfontosabb felfedezései közül válogatunk, bepillantva a kutatók kitartó, kreatív és izgalmas munkájába. Röviden kitérünk a következő 70 évre vonatkozó tervekre is. Látjuk majd, hogy mit tanulhatunk olyan atommag-ütközésekből, amelyekben néha 50 ezer, de néha csak 2 új részecske keletkezik. Emellett ízelítőt adunk a CERN-beli kísérletek elképesztő változatosságából, a klímakutatástól az antianyag gyárig, a Higgs-bozontól a neutrínókig','23','0','user','0','Dr. Veres Gábor fizikus, egyetemi tanár (ELTE TTK)','30','2024-10-25 11:15:00','2024-10-25 12:00:00','2025-02-27 20:00:00',NULL,NULL,NULL,NULL),
('228','Nyelv, Kultúra, Gondolkodás - Hogyan befolyásolja a különböző népek nyelvhasználata a világnézetüket?','Elgondolkoztál már azon, hogy milyen összefüggés lehet a latin diēs ("nap") és Zeusz neve között? Érdekel, miért írtak a görögök és a sumérok jobbra-balra váltakozó irányban a kőtábláikra? Ötleted sincs, hogy egyes bennszülött törzsek számára mit jelent a "hangyászorr", a "banánlevél" vagy a "kézanya" fogalmak? Szívesen rácsodálkoznál az emberi gondolkodás sokszínűségére? Ha bármelyik (vagy éppen egyik sem) igaz rád ezek közül, itt a helyed!','23','0','user','0','Virág Máté Gergely (12. C)','30','2024-10-25 11:15:00','2024-10-25 12:00:00','2025-02-28 20:00:00',NULL,NULL,NULL,NULL),
('229','Adatvizualizáció régen és most','Amikor valakinek sok adatot kell áttekinthető módon bemutatnia, akkor a legtöbbször valamilyen vizalizációs eszközt választ. Így van ez manapság, és így volt több mint 100 évvel ezelőtt is. Hogyan nézett ki egy 1930-as grafikon vagy térkép, és hogyan néznek ki ezek napjainkban?','23','0','user','0','Weisz Tamás (Központi Statisztikai Hivatal, Adatvizualizációs és webszerkesztőség)','30','2024-10-25 11:15:00','2024-10-25 12:00:00','2025-03-01 20:00:00',NULL,NULL,NULL,NULL),
('230','Programozzunk együtt egy scratch platformert! ','Leginkább olyanok jöjjenek, akiket érdekel ez a téma és tudnak már valamennyire programozni!','23','0','user','0','Xu Jianan (9. A)','15','2024-10-25 11:15:00','2024-10-25 12:00:00','2025-03-02 20:00:00',NULL,NULL,203,NULL),
('231','Technológia és az üzleti tanácsadás találkozása',' Képzelj el egy olyan világot, ahol a technológiai innovációk nem csak megváltoztatják a cégek működését, hanem új lehetőségeket teremtenek minden iparágban! Most lehetőséged van egy üzleti tanácsadó tapasztalatait megismerni, aki nap mint nap támogatja a vállalatokat ezeknek a technológiai megoldásoknak a bevezetésében. Az előadó nem csak a saját karrierútjáról mesél, hanem olyan készségekről és tapasztalatokról is, amelyek segíthetnek neked is sikeres karriert építeni. Ha érdekel, hogyan lehet a technológia révén hatást gyakorolni a világra, ne hagyd ki ezt az inspiráló beszélgetést!','21','0','user','0','Merkl Gabriella menedzser (KPMG Tanácsadó Kft.)','23','2024-10-26 09:00:00','2024-10-26 10:00:00','2025-01-11 20:00:00',NULL,NULL,NULL,NULL);

-- Add column remaining_seats to the table events, default value is same as the value of the column capacity
ALTER TABLE presentations ADD COLUMN remaining_capacity INT;
UPDATE presentations SET remaining_capacity = capacity;

--@block
SELECT * FROM presentations;

--@block
UPDATE presentations SET capacity = "30" WHERE id = 100;
UPDATE presentations SET remaining_capacity = capacity WHERE id = 100;