export type SiteConfig = typeof siteConfig;

interface PageSectionsType {
  teremcserek: "opened" | "closed" | "hidden";
  helyettesitesek: "opened" | "closed" | "hidden";
  menza: "opened" | "closed" | "hidden";
  esemenyek: "opened" | "closed" | "hidden";
}

const pageSections: PageSectionsType = {
  teremcserek: "hidden",
  helyettesitesek: "opened",
  menza: "opened",
  esemenyek: "opened",
};

export const siteConfig = {
  name: "Eötvös DÖ",
  description: "Az Eötvös József Gimnázium Diákönkormányzat oldala",
  pageSections: pageSections,

  users: [
    "pal.adam@e5vos.hu",
    "symons.timea.janet@e5vos.hu",
    "mikula.lajos@e5vos.hu",
    "zolyomi.peter.vilmos@e5vos.hu",

    "szepesi.abigel@e5vos.hu",
    "balogh.andrea@e5vos.hu",
    "fodor.andras.daniel@e5vos.hu",
    "sipos.anna.zita@e5vos.hu",
    "kovacs.benedek@e5vos.hu",
    "percze.haraszthy.benedek@e5vos.hu",
    "diener.blanka.lilla@e5vos.hu",
    "bujnoczki.david@e5vos.hu",
    "poser.dora@e5vos.hu",
    "harkai.emma@e5vos.hu",
    "szepesi.emilia@e5vos.hu",
    "xia.fanxiao@e5vos.hu",
    "harangozo.gergo@e5vos.hu",
    "wieszt.henrik.benedek@e5vos.hu",
    "horvath.jana@e5vos.hu",
    "xu.jianan@e5vos.hu",
    "nagy.johanna.kala@e5vos.hu",
    "ilyes.julia.borbala@e5vos.hu",
    "szabo.karolina@e5vos.hu",
    "lunczer.lilla@e5vos.hu",
    "oszlanyi.lilla@e5vos.hu",
    "barna.luca@e5vos.hu",
    "skorday.matyas@e5vos.hu",
    "magyar.natasa@e5vos.hu",
    "horvath.cziczka.nandor@e5vos.hu",
    "csermak.patrik.tamas@e5vos.hu",
    "rona.rebeka@e5vos.hu",
    "milassin.roza@e5vos.hu",
    "benedek.tamas@e5vos.hu",
    "koos.tamas@e5vos.hu",
    "kis.tamas.barnabas@e5vos.hu",
    "le.thu.anh@e5vos.hu",
    "giang.tran.nam@e5vos.hu",
    "muller.aron@e5vos.hu",
    "agoston.andras@e5vos.hu",
    "gyorke.anett.zita@e5vos.hu",
    "barany.barbara@e5vos.hu",
    "birkas.botond@e5vos.hu",
    "suszter.balint@e5vos.hu",
    "somogyi.csenge.julia@e5vos.hu",
    "kis.domonkos@e5vos.hu",
    "kovacs.dorka.21c@e5vos.hu",
    "banyai.eszter.klaudia@e5vos.hu",
    "demjan.gergely@e5vos.hu",
    "palinkas.gergely@e5vos.hu",
    "szabo.gergely@e5vos.hu",
    "lajos.hanna.gabriella@e5vos.hu",
    "telegdy.kata.zsuzsanna@e5vos.hu",
    "papay.laura@e5vos.hu",
    "milider.lilla@e5vos.hu",
    "karsai.luca.dalma@e5vos.hu",
    "fekete.lucia@e5vos.hu",
    "kovacs.miklos.21c@e5vos.hu",
    "alexa.mate@e5vos.hu",
    "mayer.mate@e5vos.hu",
    "meszaros.mate@e5vos.hu",
    "virag.mate.gergely@e5vos.hu",
    "vu.ngoc.thao.minh@e5vos.hu",
    "muszev.nikola@e5vos.hu",
    "zoikasz.nikolasz.tamas@e5vos.hu",
    "csanadi.nora@e5vos.hu",
    "hubicsak.petra.abigel@e5vos.hu",
    "tima.renata@e5vos.hu",
    "detari.szabolcs.istvan@e5vos.hu",
    "kiss.teodora@e5vos.hu",
    "csorba.vendel@e5vos.hu",
    "raski.rieger.abel@e5vos.hu",
    "deak.anna@e5vos.hu",
    "szekely.belian@e5vos.hu",
    "liu.bo.wen@e5vos.hu",
    "reti.balint@e5vos.hu",
    "torok.dorina@e5vos.hu",
    "dudla.dorottya@e5vos.hu",
    "hevizi.daniel.andor@e5vos.hu",
    "purev.ochir.erkhis@e5vos.hu",
    "prouteau.fleur.eszter@e5vos.hu",
    "bujaki.flora@e5vos.hu",
    "illes.gergo@e5vos.hu",
    "barabas.ivan@e5vos.hu",
    "eisemann.julia.kinga@e5vos.hu",
    "gayerhosz.kristof@e5vos.hu",
    "vu.le.gia.han@e5vos.hu",
    "lontai.levente@e5vos.hu",
    "kassai.leo.botond@e5vos.hu",
    "balogh.lili@e5vos.hu",
    "pentek.luca.napsugar@e5vos.hu",
    "tomoga.marcell.jozsef@e5vos.hu",
    "benedek.mate@e5vos.hu",
    "kaszap.mate@e5vos.hu",
    "simon.nimrod.zalan@e5vos.hu",
    "volk.nandor@e5vos.hu",
    "tana.orsolya@e5vos.hu",
    "nemeth.samu.levente@e5vos.hu",
    "borbely.vince@e5vos.hu",
    "hong.yezi@e5vos.hu",
    "chen.yucheng@e5vos.hu",
    "ye.zixin@e5vos.hu",
    "kovacs.zsombor@e5vos.hu",
    "rutkay.adam@e5vos.hu",
    "belle.aron@e5vos.hu",
    "czirok.adrienn@e5vos.hu",
    "botykai.andras.zeta@e5vos.hu",
    "geosits.anna.lilla@e5vos.hu",
    "szabo.balazs.istvan@e5vos.hu",
    "szirmai.balazs.oliver@e5vos.hu",
    "nguyen.bao.lam@e5vos.hu",
    "selymes.bianka@e5vos.hu",
    "megadja.blanka@e5vos.hu",
    "santa.borbala@e5vos.hu",
    "vida.balint@e5vos.hu",
    "weng.chenxin@e5vos.hu",
    "palfi.david@e5vos.hu",
    "varga.dora@e5vos.hu",
    "solymosi.kabdebo.emma@e5vos.hu",
    "solymar.eszter@e5vos.hu",
    "takacs.fanni@e5vos.hu",
    "szucs.lechner.lorin@e5vos.hu",
    "saly.luca@e5vos.hu",
    "balas.laszlo.marton@e5vos.hu",
    "varga.lena@e5vos.hu",
    "horvath.maja@e5vos.hu",
    "molnar.mihaly.boldizsar@e5vos.hu",
    "soki.milan@e5vos.hu",
    "pomozi.mate@e5vos.hu",
    "duzmath.noemi@e5vos.hu",
    "vaszi.nora@e5vos.hu",
    "pazmandi.renata@e5vos.hu",
    "katona.salamon.marton@e5vos.hu",
    "li.shiyou@e5vos.hu",
    "deak.sara.barbara@e5vos.hu",
    "lukacs.viktoria.bianka@e5vos.hu",
    "kislinder.viola@e5vos.hu",
    "cheng.yuankai@e5vos.hu",
    "szaray.zsombor.lorant@e5vos.hu",
  ],

  navItems: [
    {
      label: "Főoldal",
      href: "/",
    },
    {
      label: "Dokumentumok ⤤",
      href: "https://drive.google.com/drive/u/0/folders/0BzvbwQrx8NJEVnJfM2tSTjJsaTA",
    },
    {
      label: "Események",
      href: "/events",
    },
    {
      label: "Klubok",
      href: "/clubs",
    },
    {
      label: "Rólunk",
      href: "/about",
    },
  ],
  //navMenuItems: [],
  links: {
    github: "https://github.com/Sibosi",
    mypage: "https://linktr.ee/snimrod",
    instagram: "https://instagram.com/e5vosdo/",
    gdrive:
      "https://drive.google.com/drive/u/0/folders/0BzvbwQrx8NJEVnJfM2tSTjJsaTA",
    feedback: "https://forms.gle/XdMtAx6fsubWEBW97",
  },
};
