name: Autobackup

on:
  schedule:
    - cron: "0 21 * * 5"
  workflow_dispatch:

jobs:
  call-backup:
    runs-on: ubuntu-latest
    steps:
      - name: Call backup API
        env:
          PRODUCTION_BACKUP_API_URL: ${{ secrets.PRODUCTION_BACKUP_API_URL }}
          BACKUP_API_TOKEN: ${{ secrets.BACKUP_API_TOKEN }}
        run: |
          curl --fail --show-error --silent \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${BACKUP_API_TOKEN}" \
            "${PRODUCTION_BACKUP_API_URL}"
